// 形近词对比数据 - 只存储分组和单词名
// 单词的详细信息（音标、图片、中文）从 wordData.js 动态获取

const MINIMAL_PAIRS_DATA = [
  {
    id: "cat_group",
    name: "cat group",
    sound: "/æ/",
    example: "cat",
    words: [
      "ant",
      "aunt",
      "axe",
      "back",
      "bag",
      "bat",
      "black",
      "can",
      "cap",
      "cat",
      "catch",
      "crab",
      "dam",
      "dance",
      "fan",
      "grass",
      "hand",
      "hat",
      "jam",
      "lamp",
      "laugh",
      "map",
      "mat",
      "nap",
      "pad",
      "pan",
      "plant",
      "rag",
      "ram",
      "rat",
      "sand",
      "stand",
      "tap",
      "yak",
      "yam",
    ],
  },
  {
    id: "bird_group",
    name: "bird group",
    sound: "/ɜː/",
    example: "bird",
    words: [
      "bird",
      "earn",
      "earth",
      "girl",
      "nurse",
      "search",
      "shirt",
      "skirt",
      "stir",
      "worm",
    ],
  },
  {
    id: "dog_group",
    name: "dog group",
    sound: "/ɔː/",
    example: "dog",
    words: [
      "ball",
      "chalk",
      "corn",
      "crawl",
      "dog",
      "door",
      "draw",
      "floor",
      "fork",
      "four",
      "horse",
      "log",
      "mall",
      "pour",
      "salt",
      "shorts",
      "walk",
      "wall",
    ],
  },
  {
    id: "pot_group",
    name: "pot group",
    sound: "/ɑː/",
    example: "pot",
    words: [
      "arm",
      "box",
      "car",
      "clock",
      "cot",
      "doll",
      "dot",
      "drop",
      "farm",
      "fog",
      "fox",
      "frog",
      "hop",
      "lock",
      "March",
      "mop",
      "ox",
      "park",
      "pond",
      "pop",
      "pot",
      "rock",
      "rod",
      "scarf",
      "shark",
      "sock",
      "star",
      "swan",
      "top",
      "wash",
      "watch",
      "yacht",
    ],
  },
  {
    id: "cup_group",
    name: "cup group",
    sound: "/ʌ/",
    example: "cup",
    words: [
      "bud",
      "bug",
      "bun",
      "bus",
      "cup",
      "cut",
      "drum",
      "duck",
      "flood",
      "glove",
      "gum",
      "hug",
      "hum",
      "hut",
      "jug",
      "jump",
      "love",
      "mud",
      "mug",
      "nut",
      "one",
      "plum",
      "rug",
      "run",
      "sun",
      "thumb",
      "touch",
      "truck",
      "tub",
    ],
  },
  {
    id: "sit_group",
    name: "sit group",
    sound: "/ɪ/",
    example: "sit",
    words: [
      "beer",
      "bib",
      "blimp",
      "bring",
      "build",
      "chin",
      "cliff",
      "deer",
      "dig",
      "drink",
      "ear",
      "fig",
      "fin",
      "fish",
      "fix",
      "gift",
      "give",
      "gym",
      "hip",
      "hit",
      "ink",
      "kick",
      "kid",
      "king",
      "lick",
      "lid",
      "lift",
      "lip",
      "milk",
      "mix",
      "pig",
      "pin",
      "rib",
      "ring",
      "rip",
      "ship",
      "shrimp",
      "sing",
      "sip",
      "sit",
      "six",
      "spring",
      "swim",
      "think",
      "tip",
      "wind",
      "witch",
      "wrist",
    ],
  },
  {
    id: "pet_group",
    name: "pet group",
    sound: "/e/",
    example: "pet",
    words: [
      "bear",
      "bed",
      "belt",
      "bend",
      "bread",
      "chair",
      "chef",
      "chest",
      "desk",
      "dress",
      "egg",
      "elf",
      "hair",
      "head",
      "help",
      "hen",
      "leg",
      "neck",
      "net",
      "pear",
      "pen",
      "pet",
      "press",
      "red",
      "sell",
      "send",
      "share",
      "smell",
      "spread",
      "stair",
      "ten",
      "tent",
      "thread",
      "twelve",
      "vest",
      "vet",
    ],
  },
  {
    id: "bee_group",
    name: "bee group",
    sound: "/iː/",
    example: "bee",
    words: [
      "beach",
      "bee",
      "cheek",
      "clean",
      "eat",
      "Greece",
      "green",
      "heel",
      "key",
      "knee",
      "kneel",
      "leaf",
      "leek",
      "meat",
      "pea",
      "peach",
      "peel",
      "queen",
      "read",
      "sea",
      "seal",
      "sheep",
      "sheet",
      "sleep",
      "sweep",
      "tea",
      "three",
      "tree",
    ],
  },
  {
    id: "blue_group",
    name: "blue group",
    sound: "/uː/",
    example: "blue",
    words: [
      "blue",
      "boot",
      "broom",
      "dew",
      "glue",
      "gnu",
      "goose",
      "juice",
      "June",
      "moon",
      "school",
      "shoe",
      "spoon",
      "two",
      "zoo",
    ],
  },
  {
    id: "foot_group",
    name: "foot group",
    sound: "/ʊ/",
    example: "foot",
    words: ["cook", "foot", "look", "pull", "push", "wolf"],
  },
  {
    id: "eye_group",
    name: "eye group",
    sound: "/aɪ/",
    example: "eye",
    words: [
      "bite",
      "buy",
      "climb",
      "cry",
      "eye",
      "find",
      "five",
      "fry",
      "hide",
      "ice",
      "kite",
      "knife",
      "nine",
      "rice",
      "sky",
      "smile",
      "tie",
      "white",
      "wipe",
      "write",
    ],
  },
  {
    id: "snow_group",
    name: "snow group",
    sound: "/oʊ/",
    example: "snow",
    words: [
      "boat",
      "bowl",
      "coat",
      "comb",
      "crow",
      "goat",
      "gold",
      "hold",
      "know",
      "nose",
      "phone",
      "rose",
      "snow",
      "soap",
      "stone",
      "throw",
      "toe",
    ],
  },
  {
    id: "pay_group",
    name: "pay group",
    sound: "/eɪ/",
    example: "pay",
    words: [
      "bake",
      "break",
      "cake",
      "cave",
      "crane",
      "eight",
      "grape",
      "gray",
      "lake",
      "May",
      "nail",
      "pay",
      "plane",
      "plate",
      "rain",
      "save",
      "snail",
      "snake",
      "take",
      "tape",
      "train",
      "wave",
      "whale",
    ],
  },
  {
    id: "boy_group",
    name: "boy group",
    sound: "/ɔɪ/",
    example: "boy",
    words: ["boil", "boy"],
  },
  {
    id: "cow_group",
    name: "cow group",
    sound: "/aʊ/",
    example: "cow",
    words: [
      "brown",
      "cloud",
      "clown",
      "count",
      "cow",
      "drought",
      "house",
      "mouth",
      "owl",
    ],
  },
];

window.MINIMAL_PAIRS_DATA = MINIMAL_PAIRS_DATA;
