// 反义词数据（支持中文和美式音标）
const oppositePairs = [
  {
    name: "above_below",
    left: "above",
    right: "below",
    leftChinese: "上面",
    rightChinese: "下面",
    leftPhonetic: "/əˈbʌv/",
    rightPhonetic: "/bɪˈloʊ/",
  },
  {
    name: "alive_dead",
    left: "alive",
    right: "dead",
    leftChinese: "活着的",
    rightChinese: "死亡的",
    leftPhonetic: "/əˈlaɪv/",
    rightPhonetic: "/ded/",
  },
  {
    name: "alone_together",
    left: "alone",
    right: "together",
    leftChinese: "单独的",
    rightChinese: "一起",
    leftPhonetic: "/əˈloʊn/",
    rightPhonetic: "/təˈɡeðər/",
  },
  {
    name: "ancient_modern",
    left: "ancient",
    right: "modern",
    leftChinese: "古老的",
    rightChinese: "现代的",
    leftPhonetic: "/ˈeɪnʃənt/",
    rightPhonetic: "/ˈmɑːdərn/",
  },
  {
    name: "asleep_awake",
    left: "asleep",
    right: "awake",
    leftChinese: "睡着的",
    rightChinese: "醒着的",
    leftPhonetic: "/əˈsliːp/",
    rightPhonetic: "/əˈweɪk/",
  },
  {
    name: "beautiful_ugly",
    left: "beautiful",
    right: "ugly",
    leftChinese: "美丽的",
    rightChinese: "丑陋的",
    leftPhonetic: "/ˈbjuːtɪfəl/",
    rightPhonetic: "/ˈʌɡli/",
  },
  {
    name: "big_small",
    left: "big",
    right: "small",
    leftChinese: "大",
    rightChinese: "小",
    leftPhonetic: "/bɪɡ/",
    rightPhonetic: "/smɔːl/",
  },
  {
    name: "bright_dark",
    left: "bright",
    right: "dark",
    leftChinese: "明亮的",
    rightChinese: "黑暗的",
    leftPhonetic: "/braɪt/",
    rightPhonetic: "/dɑːrk/",
  },
  {
    name: "cheap_expensive",
    left: "cheap",
    right: "expensive",
    leftChinese: "便宜的",
    rightChinese: "昂贵的",
    leftPhonetic: "/tʃiːp/",
    rightPhonetic: "/ɪkˈspensɪv/",
  },
  {
    name: "clean_dirty",
    left: "clean",
    right: "dirty",
    leftChinese: "干净的",
    rightChinese: "脏的",
    leftPhonetic: "/kliːn/",
    rightPhonetic: "/ˈdɜːrti/",
  },
  {
    name: "dry_wet",
    left: "dry",
    right: "wet",
    leftChinese: "干的",
    rightChinese: "湿的",
    leftPhonetic: "/draɪ/",
    rightPhonetic: "/wet/",
  },
  {
    name: "empty_full",
    left: "empty",
    right: "full",
    leftChinese: "空的",
    rightChinese: "满的",
    leftPhonetic: "/ˈempti/",
    rightPhonetic: "/fʊl/",
  },
  {
    name: "fast_slow",
    left: "fast",
    right: "slow",
    leftChinese: "快的",
    rightChinese: "慢的",
    leftPhonetic: "/fæst/",
    rightPhonetic: "/sloʊ/",
  },
  {
    name: "flat_bumpy",
    left: "flat",
    right: "bumpy",
    leftChinese: "平坦的",
    rightChinese: "颠簸的",
    leftPhonetic: "/flæt/",
    rightPhonetic: "/ˈbʌmpi/",
  },
  {
    name: "front_back",
    left: "front",
    right: "back",
    leftChinese: "前面",
    rightChinese: "后面",
    leftPhonetic: "/frʌnt/",
    rightPhonetic: "/bæk/",
  },
  {
    name: "good_bad",
    left: "good",
    right: "bad",
    leftChinese: "好的",
    rightChinese: "坏的",
    leftPhonetic: "/ɡʊd/",
    rightPhonetic: "/bæd/",
  },
  {
    name: "happy_sad",
    left: "happy",
    right: "sad",
    leftChinese: "快乐的",
    rightChinese: "悲伤的",
    leftPhonetic: "/ˈhæpi/",
    rightPhonetic: "/sæd/",
  },
  {
    name: "hard_easy",
    left: "hard",
    right: "easy",
    leftChinese: "困难的",
    rightChinese: "容易的",
    leftPhonetic: "/hɑːrd/",
    rightPhonetic: "/ˈiːzi/",
  },
  {
    name: "heavy_light",
    left: "heavy",
    right: "light",
    leftChinese: "重的",
    rightChinese: "轻的",
    leftPhonetic: "/ˈhevi/",
    rightPhonetic: "/laɪt/",
  },
  {
    name: "high_low",
    left: "high",
    right: "low",
    leftChinese: "高的",
    rightChinese: "低的",
    leftPhonetic: "/haɪ/",
    rightPhonetic: "/loʊ/",
  },
  {
    name: "hot_cold",
    left: "hot",
    right: "cold",
    leftChinese: "热的",
    rightChinese: "冷的",
    leftPhonetic: "/hɑːt/",
    rightPhonetic: "/koʊld/",
  },
  {
    name: "hungry_full",
    left: "hungry",
    right: "full",
    leftChinese: "饿的",
    rightChinese: "饱的",
    leftPhonetic: "/ˈhʌŋɡri/",
    rightPhonetic: "/fʊl/",
  },
  {
    name: "kind_mean",
    left: "kind",
    right: "mean",
    leftChinese: "友善的",
    rightChinese: "刻薄的",
    leftPhonetic: "/kaɪnd/",
    rightPhonetic: "/miːn/",
  },
  {
    name: "left_right",
    left: "left",
    right: "right",
    leftChinese: "左边",
    rightChinese: "右边",
    leftPhonetic: "/left/",
    rightPhonetic: "/raɪt/",
  },
  {
    name: "loose_tight",
    left: "loose",
    right: "tight",
    leftChinese: "松的",
    rightChinese: "紧的",
    leftPhonetic: "/luːs/",
    rightPhonetic: "/taɪt/",
  },
  {
    name: "loud_quiet",
    left: "loud",
    right: "quiet",
    leftChinese: "大声的",
    rightChinese: "安静的",
    leftPhonetic: "/laʊd/",
    rightPhonetic: "/ˈkwaɪət/",
  },
  {
    name: "lucky_unlucky",
    left: "lucky",
    right: "unlucky",
    leftChinese: "幸运的",
    rightChinese: "不幸的",
    leftPhonetic: "/ˈlʌki/",
    rightPhonetic: "/ʌnˈlʌki/",
  },
  {
    name: "messy_neat",
    left: "messy",
    right: "neat",
    leftChinese: "凌乱的",
    rightChinese: "整洁的",
    leftPhonetic: "/ˈmesi/",
    rightPhonetic: "/niːt/",
  },
  {
    name: "new_old",
    left: "new",
    right: "old",
    leftChinese: "新的",
    rightChinese: "旧的",
    leftPhonetic: "/nuː/",
    rightPhonetic: "/oʊld/",
  },
  {
    name: "open_closed",
    left: "open",
    right: "closed",
    leftChinese: "开着的",
    rightChinese: "关着的",
    leftPhonetic: "/ˈoʊpən/",
    rightPhonetic: "/kloʊzd/",
  },
  {
    name: "outside_inside",
    left: "outside",
    right: "inside",
    leftChinese: "外面",
    rightChinese: "里面",
    leftPhonetic: "/ˌaʊtˈsaɪd/",
    rightPhonetic: "/ˌɪnˈsaɪd/",
  },
  {
    name: "patient_impatient",
    left: "patient",
    right: "impatient",
    leftChinese: "耐心的",
    rightChinese: "不耐烦的",
    leftPhonetic: "/ˈpeɪʃənt/",
    rightPhonetic: "/ɪmˈpeɪʃənt/",
  },
  {
    name: "real_fake",
    left: "real",
    right: "fake",
    leftChinese: "真实的",
    rightChinese: "假的",
    leftPhonetic: "/riːəl/",
    rightPhonetic: "/feɪk/",
  },
  {
    name: "rich_poor",
    left: "rich",
    right: "poor",
    leftChinese: "富有的",
    rightChinese: "贫穷的",
    leftPhonetic: "/rɪtʃ/",
    rightPhonetic: "/pʊr/",
  },
  {
    name: "right_wrong",
    left: "right",
    right: "wrong",
    leftChinese: "正确的",
    rightChinese: "错误的",
    leftPhonetic: "/raɪt/",
    rightPhonetic: "/rɔːŋ/",
  },
  {
    name: "rough_smooth",
    left: "rough",
    right: "smooth",
    leftChinese: "粗糙的",
    rightChinese: "光滑的",
    leftPhonetic: "/rʌf/",
    rightPhonetic: "/smuːð/",
  },
  {
    name: "rude_polite",
    left: "rude",
    right: "polite",
    leftChinese: "粗鲁的",
    rightChinese: "礼貌的",
    leftPhonetic: "/ruːd/",
    rightPhonetic: "/pəˈlaɪt/",
  },
  {
    name: "safe_dangerous",
    left: "safe",
    right: "dangerous",
    leftChinese: "安全的",
    rightChinese: "危险的",
    leftPhonetic: "/seɪf/",
    rightPhonetic: "/ˈdeɪndʒərəs/",
  },
  {
    name: "scared_brave",
    left: "scared",
    right: "brave",
    leftChinese: "害怕的",
    rightChinese: "勇敢的",
    leftPhonetic: "/skerd/",
    rightPhonetic: "/breɪv/",
  },
  {
    name: "shallow_deep",
    left: "shallow",
    right: "deep",
    leftChinese: "浅的",
    rightChinese: "深的",
    leftPhonetic: "/ˈʃæloʊ/",
    rightPhonetic: "/diːp/",
  },
  {
    name: "sharp_dull",
    left: "sharp",
    right: "dull",
    leftChinese: "锋利的",
    rightChinese: "钝的",
    leftPhonetic: "/ʃɑːrp/",
    rightPhonetic: "/dʌl/",
  },
  {
    name: "short_long",
    left: "short",
    right: "long",
    leftChinese: "短的",
    rightChinese: "长的",
    leftPhonetic: "/ʃɔːrt/",
    rightPhonetic: "/lɔːŋ/",
  },
  {
    name: "simple_complex",
    left: "simple",
    right: "complex",
    leftChinese: "简单的",
    rightChinese: "复杂的",
    leftPhonetic: "/ˈsɪmpəl/",
    rightPhonetic: "/kəmˈpleks/",
  },
  {
    name: "soft_hard",
    left: "soft",
    right: "hard",
    leftChinese: "柔软的",
    rightChinese: "坚硬的",
    leftPhonetic: "/sɔːft/",
    rightPhonetic: "/hɑːrd/",
  },
  {
    name: "strong_weak",
    left: "strong",
    right: "weak",
    leftChinese: "强壮的",
    rightChinese: "虚弱的",
    leftPhonetic: "/strɔːŋ/",
    rightPhonetic: "/wiːk/",
  },
  {
    name: "tall_short",
    left: "tall",
    right: "short",
    leftChinese: "高的",
    rightChinese: "矮的",
    leftPhonetic: "/tɔːl/",
    rightPhonetic: "/ʃɔːrt/",
  },
  {
    name: "thick_thin",
    left: "thick",
    right: "thin",
    leftChinese: "厚的",
    rightChinese: "薄的",
    leftPhonetic: "/θɪk/",
    rightPhonetic: "/θɪn/",
  },
  {
    name: "thin_fat",
    left: "thin",
    right: "fat",
    leftChinese: "瘦的",
    rightChinese: "胖的",
    leftPhonetic: "/θɪn/",
    rightPhonetic: "/fæt/",
  },
  {
    name: "true_false",
    left: "true",
    right: "false",
    leftChinese: "真实的",
    rightChinese: "假的",
    leftPhonetic: "/truː/",
    rightPhonetic: "/fɔːls/",
  },
  {
    name: "warm_cool",
    left: "warm",
    right: "cool",
    leftChinese: "温暖的",
    rightChinese: "凉爽的",
    leftPhonetic: "/wɔːrm/",
    rightPhonetic: "/kuːl/",
  },
  {
    name: "wide_narrow",
    left: "wide",
    right: "narrow",
    leftChinese: "宽的",
    rightChinese: "窄的",
    leftPhonetic: "/waɪd/",
    rightPhonetic: "/ˈnæroʊ/",
  },
  {
    name: "young_old",
    left: "young",
    right: "old",
    leftChinese: "年轻的",
    rightChinese: "年老的",
    leftPhonetic: "/jʌŋ/",
    rightPhonetic: "/oʊld/",
  },
  {
    name: "positive_negative",
    left: "positive",
    right: "negative",
    leftChinese: "赞成的",
    rightChinese: "反对的",
    leftPhonetic: "/ˈpɑːzətɪv/",
    rightPhonetic: "/ˈneɡətɪv/",
  },
  {
    name: "optimistic_pessimistic",
    left: "optimistic",
    right: "pessimistic",
    leftChinese: "乐观的",
    rightChinese: "悲观的",
    leftPhonetic: "/ˌɑːptɪˈmɪstɪk/",
    rightPhonetic: "/ˌpesɪˈmɪstɪk/",
  },
  {
    name: "near_far",
    left: "near",
    right: "far",
    leftChinese: "近的",
    rightChinese: "远的",
    leftPhonetic: "/nɪr/",
    rightPhonetic: "/fɑːr/",
  },
  {
    name: "delicious_disgusting",
    left: "delicious",
    right: "disgusting",
    leftChinese: "美味的",
    rightChinese: "难吃的",
    leftPhonetic: "/dɪˈlɪʃəs/",
    rightPhonetic: "/dɪsˈɡʌstɪŋ/",
  },
];

window.oppositePairs = oppositePairs;
