// 唯一数据源：所有单词信息只在这里维护
const wordData = {
  apple: {
    image: "images/apple.jpeg",
    chinese: "苹果",
    color: "#FF6B6B",
    phonetic: "/ˈæp.əl/",
    guide: "AP-uhl",
    type: "fruit",
  },
  banana: {
    image: "images/banana.jpeg",
    chinese: "香蕉",
    color: "#FFD166",
    phonetic: "/bəˈnæn.ə/",
    guide: "buh-NAH-nuh",
    type: "fruit",
  },
  orange: {
    image: "images/orange.jpeg",
    chinese: "橙子",
    color: "#FF9800",
    phonetic: "/ˈɔːr.ɪndʒ/",
    guide: "ORR-inj",
    type: "fruit",
  },
  strawberry: {
    image: "images/strawberry.jpeg",
    chinese: "草莓",
    color: "#EF476F",
    phonetic: "/ˈstrɔː.bər.i/",
    guide: "STRAW-buh-ree",
    type: "fruit",
  },
  pear: {
    image: "images/pear.jpeg",
    chinese: "梨",
    color: "#8BC34A",
    phonetic: "/per/",
    guide: "PAIR",
    type: "fruit",
  },
  peach: {
    image: "images/peach.jpeg",
    chinese: "桃子",
    color: "#FF8A65",
    phonetic: "/piːtʃ/",
    guide: "PEECH",
    type: "fruit",
  },
  grape: {
    image: "images/grape.jpeg",
    chinese: "葡萄",
    color: "#9C27B0",
    phonetic: "/ɡreɪp/",
    guide: "GRAYP",
    type: "fruit",
  },
  watermelon: {
    image: "images/watermelon.jpeg",
    chinese: "西瓜",
    color: "#4CAF50",
    phonetic: "/ˈwɔː.tər.mel.ən/",
    guide: "WAW-tuh-mel-uhn",
    type: "fruit",
  },
  pineapple: {
    image: "images/pineapple.jpeg",
    chinese: "菠萝",
    color: "#FF9800",
    phonetic: "/ˈpaɪn.æp.əl/",
    guide: "PY-nap-uhl",
    type: "fruit",
  },
  mango: {
    image: "images/mango.jpeg",
    chinese: "芒果",
    color: "#FFC107",
    phonetic: "/ˈmæŋ.ɡoʊ/",
    guide: "MANG-goh",
    type: "fruit",
  },
  kiwi: {
    image: "images/kiwi.jpeg",
    chinese: "猕猴桃",
    color: "#8BC34A",
    phonetic: "/ˈkiː.wiː/",
    guide: "KEE-wee",
    type: "fruit",
  },
  lemon: {
    image: "images/lemon.jpeg",
    chinese: "柠檬",
    color: "#FFEB3B",
    phonetic: "/ˈlem.ən/",
    guide: "LEM-uhn",
    type: "fruit",
  },
  cherry: {
    image: "images/cherry.jpeg",
    chinese: "樱桃",
    color: "#F44336",
    phonetic: "/ˈtʃer.i/",
    guide: "CHERR-ee",
    type: "fruit",
  },
  blueberry: {
    image: "images/blueberry.jpeg",
    chinese: "蓝莓",
    color: "#3F51B5",
    phonetic: "/ˈbluː.bər.i/",
    guide: "BLOO-buh-ree",
    type: "fruit",
  },
  coconut: {
    image: "images/coconut.jpeg",
    chinese: "椰子",
    color: "#795548",
    phonetic: "/ˈkoʊ.kə.nʌt/",
    guide: "KOH-kuh-nut",
    type: "fruit",
  },
  avocado: {
    image: "images/avocado.jpeg",
    chinese: "牛油果",
    color: "#4CAF50",
    phonetic: "/ˌæv.əˈkɑː.doʊ/",
    guide: "av-uh-KAH-doh",
    type: "fruit",
  },
  plum: {
    image: "images/plum.jpeg",
    chinese: "李子",
    color: "#9C27B0",
    phonetic: "/plʌm/",
    guide: "PLUM",
    type: "fruit",
  },
  apricot: {
    image: "images/apricot.jpeg",
    chinese: "杏",
    color: "#FF9800",
    phonetic: "/ˈeɪ.prɪ.kɑːt/",
    guide: "AY-pri-kot",
    type: "fruit",
  },
  grapefruit: {
    image: "images/grapefruit.jpeg",
    chinese: "西柚",
    color: "#FF5722",
    phonetic: "/ˈɡreɪp.fruːt/",
    guide: "GRAYP-froot",
    type: "fruit",
  },
  pomegranate: {
    image: "images/pomegranate.jpeg",
    chinese: "石榴",
    color: "#F44336",
    phonetic: "/ˈpɑːm.ɪ.ɡræn.ɪt/",
    guide: "POM-i-gran-it",
    type: "fruit",
  },
  lychee: {
    image: "images/lychee.jpeg",
    chinese: "荔枝",
    color: "#FF4081",
    phonetic: "/ˈliː.tʃiː/",
    guide: "LEE-chee",
    type: "fruit",
  },
  durian: {
    image: "images/durian.jpeg",
    chinese: "榴莲",
    color: "#8BC34A",
    phonetic: "/ˈdʊr.i.ən/",
    guide: "DOOR-ee-uhn",
    type: "fruit",
  },
  cantaloupe: {
    image: "images/cantaloupe.jpeg",
    chinese: "哈密瓜",
    color: "#FF9800",
    phonetic: "/ˈkæn.tə.loʊp/",
    guide: "KAN-tuh-loop",
    type: "fruit",
  },
  tomato: {
    image: "images/tomato.jpeg",
    chinese: "番茄",
    color: "#F44336",
    phonetic: "/təˈmeɪ.toʊ/",
    guide: "tuh-MAY-toh",
    type: "vegetable",
  },
  potato: {
    image: "images/potato.jpeg",
    chinese: "土豆",
    color: "#795548",
    phonetic: "/pəˈteɪ.toʊ/",
    guide: "puh-TAY-toh",
    type: "vegetable",
  },
  carrot: {
    image: "images/carrot.jpeg",
    chinese: "胡萝卜",
    color: "#FF9800",
    phonetic: "/ˈkær.ət/",
    guide: "KARR-uht",
    type: "vegetable",
  },
  onion: {
    image: "images/onion.jpeg",
    chinese: "洋葱",
    color: "#FFC107",
    phonetic: "/ˈʌn.jən/",
    guide: "UN-yuhn",
    type: "vegetable",
  },
  cabbage: {
    image: "images/cabbage.jpeg",
    chinese: "卷心菜",
    color: "#4CAF50",
    phonetic: "/ˈkæb.ɪdʒ/",
    guide: "KAB-ij",
    type: "vegetable",
  },
  lettuce: {
    image: "images/lettuce.jpeg",
    chinese: "生菜",
    color: "#8BC34A",
    phonetic: "/ˈlet.ɪs/",
    guide: "LET-iss",
    type: "vegetable",
  },
  cucumber: {
    image: "images/cucumber.jpeg",
    chinese: "黄瓜",
    color: "#4CAF50",
    phonetic: "/ˈkjuː.kʌm.bər/",
    guide: "KYOO-kum-buh",
    type: "vegetable",
  },
  pumpkin: {
    image: "images/pumpkin.jpeg",
    chinese: "南瓜",
    color: "#FF9800",
    phonetic: "/ˈpʌmp.kɪn/",
    guide: "PUMP-kin",
    type: "vegetable",
  },
  broccoli: {
    image: "images/broccoli.jpeg",
    chinese: "西兰花",
    color: "#4CAF50",
    phonetic: "/ˈbrɑː.kəl.i/",
    guide: "BRAH-kuh-lee",
    type: "vegetable",
  },
  cauliflower: {
    image: "images/cauliflower.jpeg",
    chinese: "花椰菜",
    color: "#FFE082",
    phonetic: "/ˈkɔː.lɪ.flaʊ.ər/",
    guide: "KAW-li-flow-ur",
    type: "vegetable",
  },
  spinach: {
    image: "images/spinach.jpeg",
    chinese: "菠菜",
    color: "#4CAF50",
    phonetic: "/ˈspɪn.ɪtʃ/",
    guide: "SPIN-itch",
    type: "vegetable",
  },
  eggplant: {
    image: "images/eggplant.jpeg",
    chinese: "茄子",
    color: "#9C27B0",
    phonetic: "/ˈeɡ.plænt/",
    guide: "EG-plant",
    type: "vegetable",
  },
  pepper: {
    image: "images/pepper.jpeg",
    chinese: "辣椒",
    color: "#F44336",
    phonetic: "/ˈpep.ər/",
    guide: "PEP-ur",
    type: "vegetable",
  },
  chili: {
    image: "images/chili.jpeg",
    chinese: "辣椒",
    color: "#F44336",
    phonetic: "/ˈtʃɪl.i/",
    guide: "CHIL-ee",
    type: "vegetable",
  },
  garlic: {
    image: "images/garlic.jpeg",
    chinese: "大蒜",
    color: "#FFE082",
    phonetic: "/ˈɡɑːr.lɪk/",
    guide: "GAR-lik",
    type: "vegetable",
  },
  mushroom: {
    image: "images/mushroom.jpeg",
    chinese: "蘑菇",
    color: "#795548",
    phonetic: "/ˈmʌʃ.ruːm/",
    guide: "MUSH-room",
    type: "vegetable",
  },
  corn: {
    image: "images/corn.jpeg",
    chinese: "玉米",
    color: "#FFC107",
    phonetic: "/kɔːrn/",
    guide: "KORN",
    type: "vegetable",
  },
  pea: {
    image: "images/pea.jpeg",
    chinese: "豌豆",
    color: "#4CAF50",
    phonetic: "/piː/",
    guide: "PEE",
    type: "vegetable",
  },
  radish: {
    image: "images/radish.jpeg",
    chinese: "萝卜",
    color: "#F44336",
    phonetic: "/ˈræd.ɪʃ/",
    guide: "RAD-ish",
    type: "vegetable",
  },
  leek: {
    image: "images/leek.jpeg",
    chinese: "韭菜",
    color: "#4CAF50",
    phonetic: "/liːk/",
    guide: "LEEK",
    type: "vegetable",
  },
  asparagus: {
    image: "images/asparagus.jpeg",
    chinese: "芦笋",
    color: "#4CAF50",
    phonetic: "/əˈsper.ə.ɡəs/",
    guide: "uh-SPER-uh-gus",
    type: "vegetable",
  },
  zucchini: {
    image: "images/zucchini.jpeg",
    chinese: "西葫芦",
    color: "#4CAF50",
    phonetic: "/zuːˈkiː.ni/",
    guide: "zoo-KEE-nee",
    type: "vegetable",
  },
  cat: {
    image: "images/cat.jpeg",
    chinese: "猫",
    color: "#FFD166",
    phonetic: "/kæt/",
    guide: "KAT",
    type: "animal",
  },
  dog: {
    image: "images/dog.jpeg",
    chinese: "狗",
    color: "#06D6A0",
    phonetic: "/dɔːɡ/",
    guide: "DOG",
    type: "animal",
  },
  fish: {
    image: "images/fish.jpeg",
    chinese: "鱼",
    color: "#2196F3",
    phonetic: "/fɪʃ/",
    guide: "FISH",
    type: "animal",
  },
  bird: {
    image: "images/bird.jpeg",
    chinese: "鸟",
    color: "#FF9800",
    phonetic: "/bɜːrd/",
    guide: "BURD",
    type: "animal",
  },
  lion: {
    image: "images/lion.jpeg",
    chinese: "狮子",
    color: "#FF9800",
    phonetic: "/ˈlaɪ.ən/",
    guide: "LY-uhn",
    type: "animal",
  },
  elephant: {
    image: "images/elephant.jpeg",
    chinese: "大象",
    color: "#9E9E9E",
    phonetic: "/ˈel.ɪ.fənt/",
    guide: "EL-uh-fuhnt",
    type: "animal",
  },
  fox: {
    image: "images/fox.jpeg",
    chinese: "狐狸",
    color: "#FF9800",
    phonetic: "/fɑːks/",
    guide: "FAHKS",
    type: "animal",
  },
  wolf: {
    image: "images/wolf.jpeg",
    chinese: "狼",
    color: "#9E9E9E",
    phonetic: "/wʊlf/",
    guide: "WUULF",
    type: "animal",
  },
  dolphin: {
    image: "images/dolphin.jpeg",
    chinese: "海豚",
    color: "#2196F3",
    phonetic: "/ˈdɑːl.fɪn/",
    guide: "DAHL-fin",
    type: "animal",
  },
  whale: {
    image: "images/whale.jpeg",
    chinese: "鲸鱼",
    color: "#2196F3",
    phonetic: "/weɪl/",
    guide: "WAYL",
    type: "animal",
  },
  alligator: {
    image: "images/alligator.jpeg",
    chinese: "短吻鳄",
    color: "#4CAF50",
    phonetic: "/ˈæl.ɪ.ɡeɪ.tər/",
    guide: "AL-uh-gay-tur",
    type: "animal",
  },
  rabbit: {
    image: "images/rabbit.jpeg",
    chinese: "兔子",
    color: "#FFE082",
    phonetic: "/ˈræb.ɪt/",
    guide: "RAB-it",
    type: "animal",
  },
  monkey: {
    image: "images/monkey.jpeg",
    chinese: "猴子",
    color: "#795548",
    phonetic: "/ˈmʌŋ.ki/",
    guide: "MUNG-kee",
    type: "animal",
  },
  panda: {
    image: "images/panda.jpeg",
    chinese: "熊猫",
    color: "#212121",
    phonetic: "/ˈpæn.də/",
    guide: "PAN-duh",
    type: "animal",
  },
  bear: {
    image: "images/bear.jpeg",
    chinese: "熊",
    color: "#795548",
    phonetic: "/ber/",
    guide: "BAIR",
    type: "animal",
  },
  tiger: {
    image: "images/tiger.jpeg",
    chinese: "老虎",
    color: "#FF9800",
    phonetic: "/ˈtaɪ.ɡər/",
    guide: "TY-gur",
    type: "animal",
  },
  giraffe: {
    image: "images/giraffe.jpeg",
    chinese: "长颈鹿",
    color: "#FFC107",
    phonetic: "/dʒəˈræf/",
    guide: "juh-RAF",
    type: "animal",
  },
  zebra: {
    image: "images/zebra.jpeg",
    chinese: "斑马",
    color: "#212121",
    phonetic: "/ˈziː.brə/",
    guide: "ZEE-bruh",
    type: "animal",
  },
  deer: {
    image: "images/deer.jpeg",
    chinese: "鹿",
    color: "#795548",
    phonetic: "/dɪr/",
    guide: "DEER",
    type: "animal",
  },
  kangaroo: {
    image: "images/kangaroo.jpeg",
    chinese: "袋鼠",
    color: "#795548",
    phonetic: "/ˌkæŋ.ɡəˈruː/",
    guide: "kang-guh-ROO",
    type: "animal",
  },
  snake: {
    image: "images/snake.jpeg",
    chinese: "蛇",
    color: "#4CAF50",
    phonetic: "/sneɪk/",
    guide: "SNAYK",
    type: "animal",
  },
  turtle: {
    image: "images/turtle.jpeg",
    chinese: "乌龟",
    color: "#4CAF50",
    phonetic: "/ˈtɜːr.təl/",
    guide: "TUR-tuhl",
    type: "animal",
  },
  frog: {
    image: "images/frog.jpeg",
    chinese: "青蛙",
    color: "#4CAF50",
    phonetic: "/frɔːɡ/",
    guide: "FROG",
    type: "animal",
  },
  penguin: {
    image: "images/penguin.jpeg",
    chinese: "企鹅",
    color: "#212121",
    phonetic: "/ˈpeŋ.ɡwɪn/",
    guide: "PENG-gwin",
    type: "animal",
  },
  eagle: {
    image: "images/eagle.jpeg",
    chinese: "鹰",
    color: "#795548",
    phonetic: "/ˈiː.ɡəl/",
    guide: "EE-guhl",
    type: "animal",
  },
  owl: {
    image: "images/owl.jpeg",
    chinese: "猫头鹰",
    color: "#795548",
    phonetic: "/aʊl/",
    guide: "OWL",
    type: "animal",
  },
  parrot: {
    image: "images/parrot.jpeg",
    chinese: "鹦鹉",
    color: "#F44336",
    phonetic: "/ˈper.ət/",
    guide: "PAIR-uht",
    type: "animal",
  },
  crow: {
    image: "images/crow.jpeg",
    chinese: "乌鸦",
    color: "#212121",
    phonetic: "/kroʊ/",
    guide: "KROH",
    type: "animal",
  },
  swan: {
    image: "images/swan.jpeg",
    chinese: "天鹅",
    color: "#FFFFFF",
    phonetic: "/swɑːn/",
    guide: "SWAHN",
    type: "animal",
  },
  butterfly: {
    image: "images/butterfly.jpeg",
    chinese: "蝴蝶",
    color: "#E91E63",
    phonetic: "/ˈbʌt.ər.flaɪ/",
    guide: "BUT-ur-fly",
    type: "animal",
  },
  bee: {
    image: "images/bee.jpeg",
    chinese: "蜜蜂",
    color: "#FFC107",
    phonetic: "/biː/",
    guide: "BEE",
    type: "animal",
  },
  ladybug: {
    image: "images/ladybug.jpeg",
    chinese: "瓢虫",
    color: "#F44336",
    phonetic: "/ˈleɪ.di.bʌɡ/",
    guide: "LAY-dee-bug",
    type: "animal",
  },
  ant: {
    image: "images/ant.jpeg",
    chinese: "蚂蚁",
    color: "#212121",
    phonetic: "/ænt/",
    guide: "ANT",
    type: "animal",
  },
  spider: {
    image: "images/spider.jpeg",
    chinese: "蜘蛛",
    color: "#212121",
    phonetic: "/ˈspaɪ.dər/",
    guide: "SPY-dur",
    type: "animal",
  },
  duck: {
    image: "images/duck.jpeg",
    chinese: "鸭子",
    color: "#FFC107",
    phonetic: "/dʌk/",
    guide: "DUK",
    type: "animal",
  },
  chicken: {
    image: "images/chicken.jpeg",
    chinese: "鸡",
    color: "#FFE082",
    phonetic: "/ˈtʃɪk.ɪn/",
    guide: "CHIK-in",
    type: "animal",
  },
  cow: {
    image: "images/cow.jpeg",
    chinese: "奶牛",
    color: "#FFFFFF",
    phonetic: "/kaʊ/",
    guide: "KOW",
    type: "animal",
  },
  pig: {
    image: "images/pig.jpeg",
    chinese: "猪",
    color: "#FF8A80",
    phonetic: "/pɪɡ/",
    guide: "PIG",
    type: "animal",
  },
  horse: {
    image: "images/horse.jpeg",
    chinese: "马",
    color: "#795548",
    phonetic: "/hɔːrs/",
    guide: "HORS",
    type: "animal",
  },
  sheep: {
    image: "images/sheep.jpeg",
    chinese: "羊",
    color: "#FFFFFF",
    phonetic: "/ʃiːp/",
    guide: "SHEEP",
    type: "animal",
  },
  goat: {
    image: "images/goat.jpeg",
    chinese: "山羊",
    color: "#9E9E9E",
    phonetic: "/ɡoʊt/",
    guide: "GOHT",
    type: "animal",
  },
  hen: {
    image: "images/hen.jpeg",
    chinese: "母鸡",
    color: "#FFE082",
    phonetic: "/hen/",
    guide: "HEN",
    type: "animal",
  },
  squirrel: {
    image: "images/squirrel.jpeg",
    chinese: "松鼠",
    color: "#795548",
    phonetic: "/ˈskwɜːr.əl/",
    guide: "SKWUR-uhl",
    type: "animal",
  },
  hedgehog: {
    image: "images/hedgehog.jpeg",
    chinese: "刺猬",
    color: "#795548",
    phonetic: "/ˈhedʒ.hɔːɡ/",
    guide: "HEJ-hog",
    type: "animal",
  },
  camel: {
    image: "images/camel.jpeg",
    chinese: "骆驼",
    color: "#FFC107",
    phonetic: "/ˈkæm.əl/",
    guide: "KAM-uhl",
    type: "animal",
  },
  eye: {
    image: "images/eye.jpeg",
    chinese: "眼睛",
    color: "#9C27B0",
    phonetic: "/aɪ/",
    guide: "EYE",
    type: "body",
  },
  nose: {
    image: "images/nose.jpeg",
    chinese: "鼻子",
    color: "#FF8A65",
    phonetic: "/noʊz/",
    guide: "NOHZ",
    type: "body",
  },
  ear: {
    image: "images/ear.jpeg",
    chinese: "耳朵",
    color: "#FFD166",
    phonetic: "/ɪr/",
    guide: "EER",
    type: "body",
  },
  mouth: {
    image: "images/mouth.jpeg",
    chinese: "嘴巴",
    color: "#EF476F",
    phonetic: "/maʊθ/",
    guide: "MOWTH",
    type: "body",
  },
  leg: {
    image: "images/leg.jpeg",
    chinese: "腿",
    color: "#FF9800",
    phonetic: "/leɡ/",
    guide: "LEG",
    type: "body",
  },
  foot: {
    image: "images/foot.jpeg",
    chinese: "脚",
    color: "#795548",
    phonetic: "/fʊt/",
    guide: "FOOT",
    type: "body",
  },
  bread: {
    image: "images/bread.jpeg",
    chinese: "面包",
    color: "#FFC107",
    phonetic: "/bred/",
    guide: "BRED",
    type: "food",
  },
  rice: {
    image: "images/rice.jpeg",
    chinese: "米饭",
    color: "#FFFFFF",
    phonetic: "/raɪs/",
    guide: "RICE",
    type: "food",
  },
  noodles: {
    image: "images/noodles.jpeg",
    chinese: "面条",
    color: "#FFC107",
    phonetic: "/ˈnuː.dəlz/",
    guide: "NOO-duhlz",
    type: "food",
  },
  pizza: {
    image: "images/pizza.jpeg",
    chinese: "披萨",
    color: "#FF9800",
    phonetic: "/ˈpiːt.sə/",
    guide: "PEET-suh",
    type: "food",
  },
  hamburger: {
    image: "images/hamburger.jpeg",
    chinese: "汉堡",
    color: "#795548",
    phonetic: "/ˈhæm.bɜːr.ɡər/",
    guide: "HAM-bur-gur",
    type: "food",
  },
  sandwich: {
    image: "images/sandwich.jpeg",
    chinese: "三明治",
    color: "#795548",
    phonetic: "/ˈsænd.wɪtʃ/",
    guide: "SAND-wich",
    type: "food",
  },
  meat: {
    image: "images/meat.jpeg",
    chinese: "肉",
    color: "#F44336",
    phonetic: "/miːt/",
    guide: "MEET",
    type: "food",
  },
  cookie: {
    image: "images/cookie.jpeg",
    chinese: "饼干",
    color: "#795548",
    phonetic: "/ˈkʊk.i/",
    guide: "KOO-kee",
    type: "food",
  },
  candy: {
    image: "images/candy.jpeg",
    chinese: "糖果",
    color: "#E91E63",
    phonetic: "/ˈkæn.di/",
    guide: "KAN-dee",
    type: "food",
  },
  chocolate: {
    image: "images/chocolate.jpeg",
    chinese: "巧克力",
    color: "#795548",
    phonetic: "/ˈtʃɔːk.lət/",
    guide: "CHAWK-lit",
    type: "food",
  },
  cake: {
    image: "images/cake.jpeg",
    chinese: "蛋糕",
    color: "#FF8A65",
    phonetic: "/keɪk/",
    guide: "KAYK",
    type: "food",
  },
  donut: {
    image: "images/donut.jpeg",
    chinese: "甜甜圈",
    color: "#FF9800",
    phonetic: "/ˈdoʊ.nʌt/",
    guide: "DOH-nut",
    type: "food",
  },
  popcorn: {
    image: "images/popcorn.jpeg",
    chinese: "爆米花",
    color: "#FFC107",
    phonetic: "/ˈpɑːp.kɔːrn/",
    guide: "PAHP-korn",
    type: "food",
  },
  milk: {
    image: "images/milk.jpeg",
    chinese: "牛奶",
    color: "#FFFFFF",
    phonetic: "/mɪlk/",
    guide: "MILK",
    type: "food",
  },
  juice: {
    image: "images/juice.jpeg",
    chinese: "果汁",
    color: "#FF9800",
    phonetic: "/dʒuːs/",
    guide: "JOOSE",
    type: "food",
  },
  water: {
    image: "images/water.jpeg",
    chinese: "水",
    color: "#2196F3",
    phonetic: "/ˈwɔː.tər/",
    guide: "WAW-tur",
    type: "food",
  },
  tea: {
    image: "images/tea.jpeg",
    chinese: "茶",
    color: "#795548",
    phonetic: "/tiː/",
    guide: "TEE",
    type: "food",
  },
  cup: {
    image: "images/cup.jpeg",
    chinese: "杯子",
    color: "#2196F3",
    phonetic: "/kʌp/",
    guide: "KUP",
    type: "household",
  },
  plate: {
    image: "images/plate.jpeg",
    chinese: "盘子",
    color: "#FFFFFF",
    phonetic: "/pleɪt/",
    guide: "PLAYT",
    type: "household",
  },
  bowl: {
    image: "images/bowl.jpeg",
    chinese: "碗",
    color: "#FFFFFF",
    phonetic: "/boʊl/",
    guide: "BOHL",
    type: "household",
  },
  spoon: {
    image: "images/spoon.jpeg",
    chinese: "勺子",
    color: "#9E9E9E",
    phonetic: "/spuːn/",
    guide: "SPOON",
    type: "household",
  },
  fork: {
    image: "images/fork.jpeg",
    chinese: "叉子",
    color: "#9E9E9E",
    phonetic: "/fɔːrk/",
    guide: "FORK",
    type: "household",
  },
  knife: {
    image: "images/knife.jpeg",
    chinese: "刀",
    color: "#9E9E9E",
    phonetic: "/naɪf/",
    guide: "NYFE",
    type: "household",
  },
  chopsticks: {
    image: "images/chopsticks.jpeg",
    chinese: "筷子",
    color: "#795548",
    phonetic: "/ˈtʃɑːp.stɪks/",
    guide: "CHAH-p-stiks",
    type: "household",
  },
  toothbrush: {
    image: "images/toothbrush.jpeg",
    chinese: "牙刷",
    color: "#2196F3",
    phonetic: "/ˈtuːθ.brʌʃ/",
    guide: "TOOTH-brush",
    type: "household",
  },
  toothpaste: {
    image: "images/toothpaste.jpeg",
    chinese: "牙膏",
    color: "#FFFFFF",
    phonetic: "/ˈtuːθ.peɪst/",
    guide: "TOOTH-payst",
    type: "household",
  },
  towel: {
    image: "images/towel.jpeg",
    chinese: "毛巾",
    color: "#2196F3",
    phonetic: "/ˈtaʊ.əl/",
    guide: "TOW-uhl",
    type: "household",
  },
  soap: {
    image: "images/soap.jpeg",
    chinese: "肥皂",
    color: "#FFC107",
    phonetic: "/soʊp/",
    guide: "SOHP",
    type: "household",
  },
  shampoo: {
    image: "images/shampoo.jpeg",
    chinese: "洗发水",
    color: "#2196F3",
    phonetic: "/ʃæmˈpuː/",
    guide: "sham-POO",
    type: "household",
  },
  comb: {
    image: "images/comb.jpeg",
    chinese: "梳子",
    color: "#795548",
    phonetic: "/koʊm/",
    guide: "KOHM",
    type: "household",
  },
  mirror: {
    image: "images/mirror.jpeg",
    chinese: "镜子",
    color: "#9E9E9E",
    phonetic: "/ˈmɪr.ər/",
    guide: "MIR-ur",
    type: "household",
  },
  umbrella: {
    image: "images/umbrella.jpeg",
    chinese: "雨伞",
    color: "#F44336",
    phonetic: "/ʌmˈbrel.ə/",
    guide: "um-BREL-uh",
    type: "household",
  },
  clock: {
    image: "images/clock.jpeg",
    chinese: "时钟",
    color: "#795548",
    phonetic: "/klɑːk/",
    guide: "KLAHK",
    type: "household",
  },
  lamp: {
    image: "images/lamp.jpeg",
    chinese: "台灯",
    color: "#FFC107",
    phonetic: "/læmp/",
    guide: "LAMP",
    type: "household",
  },
  phone: {
    image: "images/phone.jpeg",
    chinese: "电话",
    color: "#212121",
    phonetic: "/foʊn/",
    guide: "FOHN",
    type: "household",
  },
  computer: {
    image: "images/computer.jpeg",
    chinese: "电脑",
    color: "#212121",
    phonetic: "/kəmˈpjuː.tər/",
    guide: "kuhm-PYOO-tur",
    type: "household",
  },
  television: {
    image: "images/television.jpeg",
    chinese: "电视",
    color: "#212121",
    phonetic: "/ˈtel.ɪ.vɪʒ.ən/",
    guide: "TEL-i-vizh-uhn",
    type: "household",
  },
  remote: {
    image: "images/remote.jpeg",
    chinese: "遥控器",
    color: "#212121",
    phonetic: "/rɪˈmoʊt/",
    guide: "ri-MOHT",
    type: "household",
  },
  battery: {
    image: "images/battery.jpeg",
    chinese: "电池",
    color: "#F44336",
    phonetic: "/ˈbæt.ər.i/",
    guide: "BAT-ur-ee",
    type: "household",
  },
  key: {
    image: "images/key.jpeg",
    chinese: "钥匙",
    color: "#FFC107",
    phonetic: "/kiː/",
    guide: "KEE",
    type: "household",
  },
  lock: {
    image: "images/lock.jpeg",
    chinese: "锁",
    color: "#795548",
    phonetic: "/lɑːk/",
    guide: "LAHK",
    type: "household",
  },
  candle: {
    image: "images/candle.jpeg",
    chinese: "蜡烛",
    color: "#FFC107",
    phonetic: "/ˈkæn.dəl/",
    guide: "KAN-duhl",
    type: "household",
  },
  scissors: {
    image: "images/scissors.jpeg",
    chinese: "剪刀",
    color: "#9E9E9E",
    phonetic: "/ˈsɪz.ərz/",
    guide: "SIZ-urz",
    type: "household",
  },
  ruler: {
    image: "images/ruler.jpeg",
    chinese: "尺子",
    color: "#2196F3",
    phonetic: "/ˈruː.lər/",
    guide: "ROO-lur",
    type: "household",
  },
  eraser: {
    image: "images/eraser.jpeg",
    chinese: "橡皮",
    color: "#FFC107",
    phonetic: "/ɪˈreɪ.zər/",
    guide: "i-RAY-zur",
    type: "household",
  },
  tape: {
    image: "images/tape.jpeg",
    chinese: "胶带",
    color: "#9E9E9E",
    phonetic: "/teɪp/",
    guide: "TAYP",
    type: "household",
  },
  shirt: {
    image: "images/shirt.jpeg",
    chinese: "衬衫",
    color: "#2196F3",
    phonetic: "/ʃɜːrt/",
    guide: "SHURT",
    type: "clothing",
  },
  skirt: {
    image: "images/skirt.jpeg",
    chinese: "裙子",
    color: "#E91E63",
    phonetic: "/skɜːrt/",
    guide: "SKURT",
    type: "clothing",
  },
  dress: {
    image: "images/dress.jpeg",
    chinese: "连衣裙",
    color: "#E91E63",
    phonetic: "/dres/",
    guide: "DRES",
    type: "clothing",
  },
  shorts: {
    image: "images/shorts.jpeg",
    chinese: "短裤",
    color: "#2196F3",
    phonetic: "/ʃɔːrts/",
    guide: "SHORTS",
    type: "clothing",
  },
  jeans: {
    image: "images/jeans.jpeg",
    chinese: "牛仔裤",
    color: "#3F51B5",
    phonetic: "/dʒiːnz/",
    guide: "JEENZ",
    type: "clothing",
  },
  jacket: {
    image: "images/jacket.jpeg",
    chinese: "夹克",
    color: "#F44336",
    phonetic: "/ˈdʒæk.ɪt/",
    guide: "JAK-it",
    type: "clothing",
  },
  coat: {
    image: "images/coat.jpeg",
    chinese: "外套",
    color: "#795548",
    phonetic: "/koʊt/",
    guide: "KOHT",
    type: "clothing",
  },
  sweater: {
    image: "images/sweater.jpeg",
    chinese: "毛衣",
    color: "#F44336",
    phonetic: "/ˈswet.ər/",
    guide: "SWET-ur",
    type: "clothing",
  },
  tie: {
    image: "images/tie.jpeg",
    chinese: "领带",
    color: "#3F51B5",
    phonetic: "/taɪ/",
    guide: "TYE",
    type: "clothing",
  },
  hat: {
    image: "images/hat.jpeg",
    chinese: "帽子",
    color: "#795548",
    phonetic: "/hæt/",
    guide: "HAT",
    type: "clothing",
  },
  cap: {
    image: "images/cap.jpeg",
    chinese: "鸭舌帽",
    color: "#F44336",
    phonetic: "/kæp/",
    guide: "KAP",
    type: "clothing",
  },
  glove: {
    image: "images/glove.jpeg",
    chinese: "手套",
    color: "#F44336",
    phonetic: "/ɡlʌv/",
    guide: "GLUV",
    type: "clothing",
  },
  sock: {
    image: "images/sock.jpeg",
    chinese: "袜子",
    color: "#FFFFFF",
    phonetic: "/sɑːk/",
    guide: "SAHK",
    type: "clothing",
  },
  shoe: {
    image: "images/shoe.jpeg",
    chinese: "鞋子",
    color: "#795548",
    phonetic: "/ʃuː/",
    guide: "SHOO",
    type: "clothing",
  },
  boot: {
    image: "images/boot.jpeg",
    chinese: "靴子",
    color: "#795548",
    phonetic: "/buːt/",
    guide: "BOOT",
    type: "clothing",
  },
  slipper: {
    image: "images/slipper.jpeg",
    chinese: "拖鞋",
    color: "#FFC107",
    phonetic: "/ˈslɪp.ər/",
    guide: "SLIP-ur",
    type: "clothing",
  },
  belt: {
    image: "images/belt.jpeg",
    chinese: "皮带",
    color: "#795548",
    phonetic: "/belt/",
    guide: "BELT",
    type: "clothing",
  },
  scarf: {
    image: "images/scarf.jpeg",
    chinese: "围巾",
    color: "#F44336",
    phonetic: "/skɑːrf/",
    guide: "SKARF",
    type: "clothing",
  },
  car: {
    image: "images/car.jpeg",
    chinese: "汽车",
    color: "#FF6347",
    phonetic: "/kɑːr/",
    guide: "KAR",
    type: "transport",
  },
  bus: {
    image: "images/bus.jpeg",
    chinese: "公共汽车",
    color: "#FFC107",
    phonetic: "/bʌs/",
    guide: "BUS",
    type: "transport",
  },
  train: {
    image: "images/train.jpeg",
    chinese: "火车",
    color: "#F44336",
    phonetic: "/treɪn/",
    guide: "TRAYN",
    type: "transport",
  },
  subway: {
    image: "images/subway.jpeg",
    chinese: "地铁",
    color: "#FF9800",
    phonetic: "/ˈsʌb.weɪ/",
    guide: "SUB-way",
    type: "transport",
  },
  taxi: {
    image: "images/taxi.jpeg",
    chinese: "出租车",
    color: "#FFC107",
    phonetic: "/ˈtæk.si/",
    guide: "TAK-see",
    type: "transport",
  },
  bicycle: {
    image: "images/bicycle.jpeg",
    chinese: "自行车",
    color: "#2196F3",
    phonetic: "/ˈbaɪ.sɪ.kəl/",
    guide: "BY-sik-uhl",
    type: "transport",
  },
  motorcycle: {
    image: "images/motorcycle.jpeg",
    chinese: "摩托车",
    color: "#F44336",
    phonetic: "/ˈmoʊ.tər.saɪ.kəl/",
    guide: "MOH-tur-sy-kuhl",
    type: "transport",
  },
  plane: {
    image: "images/plane.jpeg",
    chinese: "飞机",
    color: "#2196F3",
    phonetic: "/pleɪn/",
    guide: "PLAYN",
    type: "transport",
  },
  ship: {
    image: "images/ship.jpeg",
    chinese: "轮船",
    color: "#2196F3",
    phonetic: "/ʃɪp/",
    guide: "SHIP",
    type: "transport",
  },
  boat: {
    image: "images/boat.jpeg",
    chinese: "小船",
    color: "#795548",
    phonetic: "/boʊt/",
    guide: "BOHT",
    type: "transport",
  },
  truck: {
    image: "images/truck.jpeg",
    chinese: "卡车",
    color: "#F44336",
    phonetic: "/trʌk/",
    guide: "TRUK",
    type: "transport",
  },
  ambulance: {
    image: "images/ambulance.jpeg",
    chinese: "救护车",
    color: "#F44336",
    phonetic: "/ˈæm.bjə.ləns/",
    guide: "AM-byuh-luhns",
    type: "transport",
  },
  helicopter: {
    image: "images/helicopter.jpeg",
    chinese: "直升机",
    color: "#F44336",
    phonetic: "/ˈhel.ɪ.kɑːp.tər/",
    guide: "HEL-i-kahp-tur",
    type: "transport",
  },
  moon: {
    image: "images/moon.jpeg",
    chinese: "月亮",
    color: "#FFC107",
    phonetic: "/muːn/",
    guide: "MOON",
    type: "nature",
  },
  sky: {
    image: "images/sky.jpeg",
    chinese: "天空",
    color: "#2196F3",
    phonetic: "/skaɪ/",
    guide: "SKY",
    type: "nature",
  },
  rainbow: {
    image: "images/rainbow.jpeg",
    chinese: "彩虹",
    color: "#E91E63",
    phonetic: "/ˈreɪn.boʊ/",
    guide: "RAYN-boh",
    type: "nature",
  },
  tree: {
    image: "images/tree.jpeg",
    chinese: "树",
    color: "#4CAF50",
    phonetic: "/triː/",
    guide: "TREE",
    type: "nature",
  },
  leaf: {
    image: "images/leaf.jpeg",
    chinese: "叶子",
    color: "#4CAF50",
    phonetic: "/liːf/",
    guide: "LEEF",
    type: "nature",
  },
  grass: {
    image: "images/grass.jpeg",
    chinese: "草",
    color: "#4CAF50",
    phonetic: "/ɡræs/",
    guide: "GRASS",
    type: "nature",
  },
  mountain: {
    image: "images/mountain.jpeg",
    chinese: "山",
    color: "#795548",
    phonetic: "/ˈmaʊn.tən/",
    guide: "MOUN-tuhn",
    type: "nature",
  },
  sea: {
    image: "images/sea.jpeg",
    chinese: "大海",
    color: "#2196F3",
    phonetic: "/siː/",
    guide: "SEE",
    type: "nature",
  },
  star: {
    image: "images/star.jpeg",
    chinese: "星星",
    color: "#FFC107",
    phonetic: "/stɑːr/",
    guide: "STAR",
    type: "nature",
  },
  cloud: {
    image: "images/cloud.jpeg",
    chinese: "云",
    color: "#FFFFFF",
    phonetic: "/klaʊd/",
    guide: "KLOWD",
    type: "nature",
  },
  rain: {
    image: "images/rain.jpeg",
    chinese: "雨",
    color: "#2196F3",
    phonetic: "/reɪn/",
    guide: "RAYN",
    type: "nature",
  },
  snow: {
    image: "images/snow.jpeg",
    chinese: "雪",
    color: "#FFFFFF",
    phonetic: "/snoʊ/",
    guide: "SNOH",
    type: "nature",
  },
  wind: {
    image: "images/wind.jpeg",
    chinese: "风",
    color: "#9E9E9E",
    phonetic: "/wɪnd/",
    guide: "WIND",
    type: "nature",
  },
  thunder: {
    image: "images/thunder.jpeg",
    chinese: "雷",
    color: "#FFC107",
    phonetic: "/ˈθʌn.dər/",
    guide: "THUN-dur",
    type: "nature",
  },
  lightning: {
    image: "images/lightning.jpeg",
    chinese: "闪电",
    color: "#FFC107",
    phonetic: "/ˈlaɪt.nɪŋ/",
    guide: "LYT-ning",
    type: "nature",
  },
  fog: {
    image: "images/fog.jpeg",
    chinese: "雾",
    color: "#9E9E9E",
    phonetic: "/fɑːɡ/",
    guide: "FAHG",
    type: "nature",
  },
  river: {
    image: "images/river.jpeg",
    chinese: "河流",
    color: "#2196F3",
    phonetic: "/ˈrɪv.ər/",
    guide: "RIV-ur",
    type: "nature",
  },
  lake: {
    image: "images/lake.jpeg",
    chinese: "湖",
    color: "#2196F3",
    phonetic: "/leɪk/",
    guide: "LAYK",
    type: "nature",
  },
  egg: {
    image: "images/egg.jpeg",
    chinese: "鸡蛋",
    color: "#FFE082",
    phonetic: "/eɡ/",
    guide: "EG",
    type: "food",
  },
  house: {
    image: "images/house.jpeg",
    chinese: "房子",
    color: "#FF8A65",
    phonetic: "/haʊs/",
    guide: "HOWSS",
    type: "household",
  },
  flower: {
    image: "images/flower.jpeg",
    chinese: "花",
    color: "#E91E63",
    phonetic: "/ˈflaʊ.ər/",
    guide: "FLOW-ur",
    type: "nature",
  },
  ball: {
    image: "images/ball.jpeg",
    chinese: "球",
    color: "#4ECDC4",
    phonetic: "/bɔːl/",
    guide: "BAWL",
    type: "other",
  },
  sun: {
    image: "images/sun.jpeg",
    chinese: "太阳",
    color: "#FFD700",
    phonetic: "/sʌn/",
    guide: "SUN",
    type: "nature",
  },
  brother: {
    image: "images/brother.jpeg",
    chinese: "兄弟",
    color: "#2196F3",
    phonetic: "/ˈbrʌð.ər/",
    guide: "BRUH-thur",
    type: "people",
  },
  mother: {
    image: "images/mother.jpeg",
    chinese: "母亲",
    color: "#E91E63",
    phonetic: "/ˈmʌð.ər/",
    guide: "MUH-thur",
    type: "people",
  },
  father: {
    image: "images/father.jpeg",
    chinese: "父亲",
    color: "#2196F3",
    phonetic: "/ˈfɑː.ðər/",
    guide: "FAH-thur",
    type: "people",
  },
  grandpa: {
    image: "images/grandpa.jpeg",
    chinese: "爷爷",
    color: "#795548",
    phonetic: "/ˈɡræn.pɑː/",
    guide: "GRAN-pah",
    type: "people",
  },
  grandma: {
    image: "images/grandma.jpeg",
    chinese: "奶奶",
    color: "#795548",
    phonetic: "/ˈɡræn.mɑː/",
    guide: "GRAN-mah",
    type: "people",
  },
  uncle: {
    image: "images/uncle.jpeg",
    chinese: "叔叔",
    color: "#FF9800",
    phonetic: "/ˈʌŋ.kəl/",
    guide: "UNG-kuhl",
    type: "people",
  },
  aunt: {
    image: "images/aunt.jpeg",
    chinese: "阿姨",
    color: "#FF9800",
    phonetic: "/ænt/",
    guide: "ANT",
    type: "people",
  },
  sister: {
    image: "images/sister.jpeg",
    chinese: "姐妹",
    color: "#E91E63",
    phonetic: "/ˈsɪs.tər/",
    guide: "SIS-tur",
    type: "people",
  },
  family: {
    image: "images/family.jpeg",
    chinese: "家庭",
    color: "#E91E63",
    phonetic: "/ˈfæm.əl.i/",
    guide: "FAM-uh-lee",
    type: "people",
  },
  queen: {
    image: "images/queen.jpeg",
    chinese: "女王",
    color: "#9C27B0",
    phonetic: "/kwiːn/",
    guide: "KWEEN",
    type: "people",
  },
  king: {
    image: "images/king.jpeg",
    chinese: "国王",
    color: "#FF9800",
    phonetic: "/kɪŋ/",
    guide: "KING",
    type: "people",
  },
  giant: {
    image: "images/giant.jpeg",
    chinese: "巨人",
    color: "#4CAF50",
    phonetic: "/ˈdʒaɪ.ənt/",
    guide: "JY-uhnt",
    type: "people",
  },
  elf: {
    image: "images/elf.jpeg",
    chinese: "精灵",
    color: "#4CAF50",
    phonetic: "/elf/",
    guide: "ELF",
    type: "people",
  },
  witch: {
    image: "images/witch.jpeg",
    chinese: "女巫",
    color: "#9C27B0",
    phonetic: "/wɪtʃ/",
    guide: "WICH",
    type: "people",
  },
  wizard: {
    image: "images/wizard.jpeg",
    chinese: "巫师",
    color: "#3F51B5",
    phonetic: "/ˈwɪz.ərd/",
    guide: "WIZ-urd",
    type: "people",
  },
  clown: {
    image: "images/clown.jpeg",
    chinese: "小丑",
    color: "#F44336",
    phonetic: "/klaʊn/",
    guide: "KLOWN",
    type: "people",
  },
  soldier: {
    image: "images/soldier.jpeg",
    chinese: "士兵",
    color: "#795548",
    phonetic: "/ˈsoʊl.dʒər/",
    guide: "SOHL-jur",
    type: "people",
  },
  teacher: {
    image: "images/teacher.jpeg",
    chinese: "老师",
    color: "#2196F3",
    phonetic: "/ˈtiː.tʃər/",
    guide: "TEE-chur",
    type: "people",
  },
  doctor: {
    image: "images/doctor.jpeg",
    chinese: "医生",
    color: "#4CAF50",
    phonetic: "/ˈdɑːk.tər/",
    guide: "DAHK-tur",
    type: "people",
  },
  nurse: {
    image: "images/nurse.jpeg",
    chinese: "护士",
    color: "#E91E63",
    phonetic: "/nɜːrs/",
    guide: "NURS",
    type: "people",
  },
  farmer: {
    image: "images/farmer.jpeg",
    chinese: "农民",
    color: "#795548",
    phonetic: "/ˈfɑːr.mər/",
    guide: "FAR-mur",
    type: "people",
  },
  chef: {
    image: "images/chef.jpeg",
    chinese: "厨师",
    color: "#FF9800",
    phonetic: "/ʃef/",
    guide: "SHEF",
    type: "people",
  },
  pilot: {
    image: "images/pilot.jpeg",
    chinese: "飞行员",
    color: "#2196F3",
    phonetic: "/ˈpaɪ.lət/",
    guide: "PY-luht",
    type: "people",
  },
  driver: {
    image: "images/driver.jpeg",
    chinese: "司机",
    color: "#795548",
    phonetic: "/ˈdraɪ.vər/",
    guide: "DRY-vur",
    type: "people",
  },
  crab: {
    image: "images/crab.jpeg",
    chinese: "螃蟹",
    color: "#F44336",
    phonetic: "/kræb/",
    guide: "KRAB",
    type: "animal",
  },
  lobster: {
    image: "images/lobster.jpeg",
    chinese: "龙虾",
    color: "#F44336",
    phonetic: "/ˈlɑːb.stər/",
    guide: "LAHB-stur",
    type: "animal",
  },
  shrimp: {
    image: "images/shrimp.jpeg",
    chinese: "虾",
    color: "#FF9800",
    phonetic: "/ʃrɪmp/",
    guide: "SHRIMP",
    type: "animal",
  },
  octopus: {
    image: "images/octopus.jpeg",
    chinese: "章鱼",
    color: "#9C27B0",
    phonetic: "/ˈɑːk.tə.pəs/",
    guide: "AHK-tuh-puhs",
    type: "animal",
  },
  squid: {
    image: "images/squid.jpeg",
    chinese: "鱿鱼",
    color: "#9C27B0",
    phonetic: "/skwɪd/",
    guide: "SKWID",
    type: "animal",
  },
  seal: {
    image: "images/seal.jpeg",
    chinese: "海豹",
    color: "#9E9E9E",
    phonetic: "/siːl/",
    guide: "SEEL",
    type: "animal",
  },
  walrus: {
    image: "images/walrus.jpeg",
    chinese: "海象",
    color: "#795548",
    phonetic: "/ˈwɔːl.rəs/",
    guide: "WAWL-ruhs",
    type: "animal",
  },
  otter: {
    image: "images/otter.jpeg",
    chinese: "水獭",
    color: "#795548",
    phonetic: "/ˈɑː.tər/",
    guide: "AH-tur",
    type: "animal",
  },
  bat: {
    image: "images/bat.jpeg",
    chinese: "蝙蝠",
    color: "#212121",
    phonetic: "/bæt/",
    guide: "BAT",
    type: "animal",
  },
  rat: {
    image: "images/rat.jpeg",
    chinese: "老鼠",
    color: "#795548",
    phonetic: "/ræt/",
    guide: "RAT",
    type: "animal",
  },
  hamster: {
    image: "images/hamster.jpeg",
    chinese: "仓鼠",
    color: "#FFC107",
    phonetic: "/ˈhæm.stər/",
    guide: "HAM-stur",
    type: "animal",
  },
  ferret: {
    image: "images/ferret.jpeg",
    chinese: "雪貂",
    color: "#FFC107",
    phonetic: "/ˈfer.ɪt/",
    guide: "FER-it",
    type: "animal",
  },
  pony: {
    image: "images/pony.jpeg",
    chinese: "小马",
    color: "#795548",
    phonetic: "/ˈpoʊ.ni/",
    guide: "POH-nee",
    type: "animal",
  },
  donkey: {
    image: "images/donkey.jpeg",
    chinese: "驴",
    color: "#9E9E9E",
    phonetic: "/ˈdɑːŋ.ki/",
    guide: "DAHNG-kee",
    type: "animal",
  },
  goose: {
    image: "images/goose.jpeg",
    chinese: "鹅",
    color: "#FFFFFF",
    phonetic: "/ɡuːs/",
    guide: "GOOSS",
    type: "animal",
  },
  pigeon: {
    image: "images/pigeon.jpeg",
    chinese: "鸽子",
    color: "#9E9E9E",
    phonetic: "/ˈpɪdʒ.ɪn/",
    guide: "PIJ-in",
    type: "animal",
  },
  seagull: {
    image: "images/seagull.jpeg",
    chinese: "海鸥",
    color: "#FFFFFF",
    phonetic: "/ˈsiː.ɡʌl/",
    guide: "SEE-guhl",
    type: "animal",
  },
  woodpecker: {
    image: "images/woodpecker.jpeg",
    chinese: "啄木鸟",
    color: "#F44336",
    phonetic: "/ˈwʊd.pek.ər/",
    guide: "WOOD-pek-ur",
    type: "animal",
  },
  peacock: {
    image: "images/peacock.jpeg",
    chinese: "孔雀",
    color: "#2196F3",
    phonetic: "/ˈpiː.kɑːk/",
    guide: "PEE-kahk",
    type: "animal",
  },
  firefly: {
    image: "images/firefly.jpeg",
    chinese: "萤火虫",
    color: "#FFC107",
    phonetic: "/ˈfaɪər.flaɪ/",
    guide: "FY-ur-fly",
    type: "animal",
  },
  caterpillar: {
    image: "images/caterpillar.jpeg",
    chinese: "毛毛虫",
    color: "#4CAF50",
    phonetic: "/ˈkæt.ər.pɪl.ər/",
    guide: "KAT-ur-pil-ur",
    type: "animal",
  },
  snail: {
    image: "images/snail.jpeg",
    chinese: "蜗牛",
    color: "#795548",
    phonetic: "/sneɪl/",
    guide: "SNAYL",
    type: "animal",
  },
  worm: {
    image: "images/worm.jpeg",
    chinese: "蠕虫",
    color: "#795548",
    phonetic: "/wɜːrm/",
    guide: "WURM",
    type: "animal",
  },
  dinosaur: {
    image: "images/dinosaur.jpeg",
    chinese: "恐龙",
    color: "#4CAF50",
    phonetic: "/ˈdaɪ.nə.sɔːr/",
    guide: "DY-nuh-sawr",
    type: "animal",
  },
  date: {
    image: "images/date.jpeg",
    chinese: "枣",
    color: "#795548",
    phonetic: "/deɪt/",
    guide: "DAYT",
    type: "fruit",
  },
  papaya: {
    image: "images/papaya.jpeg",
    chinese: "木瓜",
    color: "#FF9800",
    phonetic: "/pəˈpaɪ.ə/",
    guide: "puh-PY-uh",
    type: "fruit",
  },
  nectarine: {
    image: "images/nectarine.jpeg",
    chinese: "油桃",
    color: "#FF9800",
    phonetic: "/ˈnek.tər.iːn/",
    guide: "NEK-tur-een",
    type: "fruit",
  },
  olive: {
    image: "images/olive.jpeg",
    chinese: "橄榄",
    color: "#4CAF50",
    phonetic: "/ˈɑː.lɪv/",
    guide: "AH-liv",
    type: "fruit",
  },
  celery: {
    image: "images/celery.jpeg",
    chinese: "芹菜",
    color: "#4CAF50",
    phonetic: "/ˈsel.ər.i/",
    guide: "SEL-ur-ee",
    type: "vegetable",
  },
  okra: {
    image: "images/okra.jpeg",
    chinese: "秋葵",
    color: "#4CAF50",
    phonetic: "/ˈoʊ.krə/",
    guide: "OH-kruh",
    type: "vegetable",
  },
  shallot: {
    image: "images/shallot.jpeg",
    chinese: "青葱",
    color: "#FF9800",
    phonetic: "/ʃəˈlɑːt/",
    guide: "shuh-LAHT",
    type: "vegetable",
  },
  endive: {
    image: "images/endive.jpeg",
    chinese: "菊苣",
    color: "#4CAF50",
    phonetic: "/ˈen.daɪv/",
    guide: "EN-dyv",
    type: "vegetable",
  },
  bed: {
    image: "images/bed.jpeg",
    chinese: "床",
    color: "#795548",
    phonetic: "/bed/",
    guide: "BED",
    type: "household",
  },
  desk: {
    image: "images/desk.jpeg",
    chinese: "书桌",
    color: "#795548",
    phonetic: "/desk/",
    guide: "DESK",
    type: "household",
  },
  chair: {
    image: "images/chair.jpeg",
    chinese: "椅子",
    color: "#795548",
    phonetic: "/tʃer/",
    guide: "CHAIR",
    type: "household",
  },
  sofa: {
    image: "images/sofa.jpeg",
    chinese: "沙发",
    color: "#795548",
    phonetic: "/ˈsoʊ.fə/",
    guide: "SOH-fuh",
    type: "household",
  },
  blanket: {
    image: "images/blanket.jpeg",
    chinese: "毯子",
    color: "#2196F3",
    phonetic: "/ˈblæŋ.kɪt/",
    guide: "BLANG-kit",
    type: "household",
  },
  pillow: {
    image: "images/pillow.jpeg",
    chinese: "枕头",
    color: "#FFFFFF",
    phonetic: "/ˈpɪl.oʊ/",
    guide: "PIL-oh",
    type: "household",
  },
  sheet: {
    image: "images/sheet.jpeg",
    chinese: "床单",
    color: "#FFFFFF",
    phonetic: "/ʃiːt/",
    guide: "SHEET",
    type: "household",
  },
  sponge: {
    image: "images/sponge.jpeg",
    chinese: "海绵",
    color: "#FFC107",
    phonetic: "/spʌndʒ/",
    guide: "SPUNJ",
    type: "household",
  },
  bucket: {
    image: "images/bucket.jpeg",
    chinese: "水桶",
    color: "#2196F3",
    phonetic: "/ˈbʌk.ɪt/",
    guide: "BUK-it",
    type: "household",
  },
  broom: {
    image: "images/broom.jpeg",
    chinese: "扫帚",
    color: "#795548",
    phonetic: "/bruːm/",
    guide: "BROOM",
    type: "household",
  },
  mop: {
    image: "images/mop.jpeg",
    chinese: "拖把",
    color: "#2196F3",
    phonetic: "/mɑːp/",
    guide: "MAHP",
    type: "household",
  },
  detergent: {
    image: "images/detergent.jpeg",
    chinese: "洗涤剂",
    color: "#2196F3",
    phonetic: "/dɪˈtɜːr.dʒənt/",
    guide: "di-TUR-juhnt",
    type: "household",
  },
  clothespin: {
    image: "images/clothespin.jpeg",
    chinese: "衣夹",
    color: "#795548",
    phonetic: "/ˈkloʊðz.pɪn/",
    guide: "KLOHTHZ-pin",
    type: "household",
  },
  hanger: {
    image: "images/hanger.jpeg",
    chinese: "衣架",
    color: "#9E9E9E",
    phonetic: "/ˈhæŋ.ər/",
    guide: "HANG-ur",
    type: "household",
  },
  iron: {
    image: "images/iron.jpeg",
    chinese: "熨斗",
    color: "#9E9E9E",
    phonetic: "/ˈaɪ.ərn/",
    guide: "EYE-urn",
    type: "household",
  },
  needle: {
    image: "images/needle.jpeg",
    chinese: "针",
    color: "#9E9E9E",
    phonetic: "/ˈniː.dəl/",
    guide: "NEE-dul",
    type: "household",
  },
  thread: {
    image: "images/thread.jpeg",
    chinese: "线",
    color: "#F44336",
    phonetic: "/θred/",
    guide: "THRED",
    type: "household",
  },
  button: {
    image: "images/button.jpeg",
    chinese: "纽扣",
    color: "#F44336",
    phonetic: "/ˈbʌt.ən/",
    guide: "BUT-uhn",
    type: "household",
  },
  zipper: {
    image: "images/zipper.jpeg",
    chinese: "拉链",
    color: "#9E9E9E",
    phonetic: "/ˈzɪp.ər/",
    guide: "ZIP-ur",
    type: "household",
  },
  wallet: {
    image: "images/wallet.jpeg",
    chinese: "钱包",
    color: "#795548",
    phonetic: "/ˈwɑː.lɪt/",
    guide: "WAH-lit",
    type: "household",
  },
  backpack: {
    image: "images/backpack.jpeg",
    chinese: "背包",
    color: "#F44336",
    phonetic: "/ˈbæk.pæk/",
    guide: "BAK-pak",
    type: "household",
  },
  suitcase: {
    image: "images/suitcase.jpeg",
    chinese: "手提箱",
    color: "#795548",
    phonetic: "/ˈsuːt.keɪs/",
    guide: "SOOT-kayss",
    type: "household",
  },
  ladder: {
    image: "images/ladder.jpeg",
    chinese: "梯子",
    color: "#795548",
    phonetic: "/ˈlæd.ər/",
    guide: "LAD-ur",
    type: "household",
  },
  hammer: {
    image: "images/hammer.jpeg",
    chinese: "锤子",
    color: "#795548",
    phonetic: "/ˈhæm.ər/",
    guide: "HAM-ur",
    type: "household",
  },
  nail: {
    image: "images/nail.jpeg",
    chinese: "钉子",
    color: "#9E9E9E",
    phonetic: "/neɪl/",
    guide: "NAYL",
    type: "household",
  },
  screwdriver: {
    image: "images/screwdriver.jpeg",
    chinese: "螺丝刀",
    color: "#795548",
    phonetic: "/ˈskruː.draɪ.vər/",
    guide: "SKROO-dry-vur",
    type: "household",
  },
  wrench: {
    image: "images/wrench.jpeg",
    chinese: "扳手",
    color: "#9E9E9E",
    phonetic: "/rentʃ/",
    guide: "RENCH",
    type: "household",
  },
  pliers: {
    image: "images/pliers.jpeg",
    chinese: "钳子",
    color: "#9E9E9E",
    phonetic: "/ˈplaɪ.ərz/",
    guide: "PLY-urz",
    type: "household",
  },
  crayon: {
    image: "images/crayon.jpeg",
    chinese: "蜡笔",
    color: "#F44336",
    phonetic: "/ˈkreɪ.ɑːn/",
    guide: "KRAY-ahn",
    type: "household",
  },
  chalk: {
    image: "images/chalk.jpeg",
    chinese: "粉笔",
    color: "#FFFFFF",
    phonetic: "/tʃɔːk/",
    guide: "CHAWK",
    type: "household",
  },
  glue: {
    image: "images/glue.jpeg",
    chinese: "胶水",
    color: "#FFC107",
    phonetic: "/ɡluː/",
    guide: "GLOO",
    type: "household",
  },
  vest: {
    image: "images/vest.jpeg",
    chinese: "背心",
    color: "#2196F3",
    phonetic: "/vest/",
    guide: "VEST",
    type: "clothing",
  },
  raincoat: {
    image: "images/raincoat.jpeg",
    chinese: "雨衣",
    color: "#FFC107",
    phonetic: "/ˈreɪn.koʊt/",
    guide: "RAYN-koht",
    type: "clothing",
  },
  pajamas: {
    image: "images/pajamas.jpeg",
    chinese: "睡衣",
    color: "#2196F3",
    phonetic: "/pəˈdʒɑː.məz/",
    guide: "puh-JAH-muhz",
    type: "clothing",
  },
  swimsuit: {
    image: "images/swimsuit.jpeg",
    chinese: "泳衣",
    color: "#2196F3",
    phonetic: "/ˈswɪm.suːt/",
    guide: "SWIM-soot",
    type: "clothing",
  },
  underwear: {
    image: "images/underwear.jpeg",
    chinese: "内衣",
    color: "#FFFFFF",
    phonetic: "/ˈʌn.dər.wer/",
    guide: "UN-dur-wair",
    type: "clothing",
  },
  overalls: {
    image: "images/overalls.jpeg",
    chinese: "工装裤",
    color: "#2196F3",
    phonetic: "/ˈoʊ.vər.ɔːlz/",
    guide: "OH-vur-awlz",
    type: "clothing",
  },
  helmet: {
    image: "images/helmet.jpeg",
    chinese: "头盔",
    color: "#F44336",
    phonetic: "/ˈhel.mɪt/",
    guide: "HEL-mit",
    type: "clothing",
  },
  earring: {
    image: "images/earring.jpeg",
    chinese: "耳环",
    color: "#FFC107",
    phonetic: "/ˈɪr.rɪŋ/",
    guide: "EER-ring",
    type: "clothing",
  },
  necklace: {
    image: "images/necklace.jpeg",
    chinese: "项链",
    color: "#FFC107",
    phonetic: "/ˈnek.lɪs/",
    guide: "NEK-lis",
    type: "clothing",
  },
  bracelet: {
    image: "images/bracelet.jpeg",
    chinese: "手镯",
    color: "#FFC107",
    phonetic: "/ˈbreɪs.lɪt/",
    guide: "BRAYSS-lit",
    type: "clothing",
  },
  ring: {
    image: "images/ring.jpeg",
    chinese: "戒指",
    color: "#FFC107",
    phonetic: "/rɪŋ/",
    guide: "RING",
    type: "clothing",
  },
  watch: {
    image: "images/watch.jpeg",
    chinese: "手表",
    color: "#795548",
    phonetic: "/wɑːtʃ/",
    guide: "WAHCH",
    type: "clothing",
  },
  glasses: {
    image: "images/glasses.jpeg",
    chinese: "眼镜",
    color: "#795548",
    phonetic: "/ˈɡlæs.ɪz/",
    guide: "GLASS-iz",
    type: "clothing",
  },
  suspenders: {
    image: "images/suspenders.jpeg",
    chinese: "吊带裤",
    color: "#795548",
    phonetic: "/səˈspen.dərz/",
    guide: "suh-SPEN-durz",
    type: "clothing",
  },
  handkerchief: {
    image: "images/handkerchief.jpeg",
    chinese: "手帕",
    color: "#FFFFFF",
    phonetic: "/ˈhæŋ.kər.tʃiːf/",
    guide: "HANG-kur-cheef",
    type: "clothing",
  },
  scooter: {
    image: "images/scooter.jpeg",
    chinese: "滑板车",
    color: "#F44336",
    phonetic: "/ˈskuː.tər/",
    guide: "SKOO-tur",
    type: "transport",
  },
  skateboard: {
    image: "images/skateboard.jpeg",
    chinese: "滑板",
    color: "#F44336",
    phonetic: "/ˈskeɪt.bɔːrd/",
    guide: "SKAYT-bord",
    type: "transport",
  },
  sailboat: {
    image: "images/sailboat.jpeg",
    chinese: "帆船",
    color: "#2196F3",
    phonetic: "/ˈseɪl.boʊt/",
    guide: "SAYL-boht",
    type: "transport",
  },
  yacht: {
    image: "images/yacht.jpeg",
    chinese: "游艇",
    color: "#FFFFFF",
    phonetic: "/jɑːt/",
    guide: "YAHT",
    type: "transport",
  },
  submarine: {
    image: "images/submarine.jpeg",
    chinese: "潜艇",
    color: "#2196F3",
    phonetic: "/ˌsʌb.məˈriːn/",
    guide: "sub-muh-REEN",
    type: "transport",
  },
  blimp: {
    image: "images/blimp.jpeg",
    chinese: "飞艇",
    color: "#FFFFFF",
    phonetic: "/blɪmp/",
    guide: "BLIMP",
    type: "transport",
  },
  rocket: {
    image: "images/rocket.jpeg",
    chinese: "火箭",
    color: "#F44336",
    phonetic: "/ˈrɑː.kɪt/",
    guide: "RAH-kit",
    type: "transport",
  },
  tractor: {
    image: "images/tractor.jpeg",
    chinese: "拖拉机",
    color: "#F44336",
    phonetic: "/ˈtræk.tər/",
    guide: "TRAK-tur",
    type: "transport",
  },
  bulldozer: {
    image: "images/bulldozer.jpeg",
    chinese: "推土机",
    color: "#FFC107",
    phonetic: "/ˈbʊl.doʊ.zər/",
    guide: "BOOL-doh-zur",
    type: "transport",
  },
  crane: {
    image: "images/crane.jpeg",
    chinese: "起重机",
    color: "#FFC107",
    phonetic: "/kreɪn/",
    guide: "KRAYN",
    type: "transport",
  },
  forklift: {
    image: "images/forklift.jpeg",
    chinese: "叉车",
    color: "#FFC107",
    phonetic: "/ˈfɔːrk.lɪft/",
    guide: "FORK-lift",
    type: "transport",
  },
  convertible: {
    image: "images/convertible.jpeg",
    chinese: "敞篷车",
    color: "#F44336",
    phonetic: "/kənˈvɜːr.tə.bəl/",
    guide: "kuhn-VUR-tuh-buhl",
    type: "transport",
  },
  island: {
    image: "images/island.jpeg",
    chinese: "岛屿",
    color: "#4CAF50",
    phonetic: "/ˈaɪ.lənd/",
    guide: "EYE-luhnd",
    type: "nature",
  },
  beach: {
    image: "images/beach.jpeg",
    chinese: "海滩",
    color: "#FFC107",
    phonetic: "/biːtʃ/",
    guide: "BEECH",
    type: "nature",
  },
  cliff: {
    image: "images/cliff.jpeg",
    chinese: "悬崖",
    color: "#795548",
    phonetic: "/klɪf/",
    guide: "KLIF",
    type: "nature",
  },
  cave: {
    image: "images/cave.jpeg",
    chinese: "洞穴",
    color: "#212121",
    phonetic: "/keɪv/",
    guide: "KAYV",
    type: "nature",
  },
  desert: {
    image: "images/desert.jpeg",
    chinese: "沙漠",
    color: "#FFC107",
    phonetic: "/ˈdez.ərt/",
    guide: "DEZ-urt",
    type: "nature",
  },
  forest: {
    image: "images/forest.jpeg",
    chinese: "森林",
    color: "#4CAF50",
    phonetic: "/ˈfɔːr.ɪst/",
    guide: "FOR-ist",
    type: "nature",
  },
  waterfall: {
    image: "images/waterfall.jpeg",
    chinese: "瀑布",
    color: "#2196F3",
    phonetic: "/ˈwɔː.tər.fɔːl/",
    guide: "WAW-tur-fawl",
    type: "nature",
  },
  stream: {
    image: "images/stream.jpeg",
    chinese: "溪流",
    color: "#2196F3",
    phonetic: "/striːm/",
    guide: "STREEM",
    type: "nature",
  },
  pond: {
    image: "images/pond.jpeg",
    chinese: "池塘",
    color: "#2196F3",
    phonetic: "/pɑːnd/",
    guide: "PAHND",
    type: "nature",
  },
  wave: {
    image: "images/wave.jpeg",
    chinese: "波浪",
    color: "#2196F3",
    phonetic: "/weɪv/",
    guide: "WAYV",
    type: "nature",
  },
  sand: {
    image: "images/sand.jpeg",
    chinese: "沙子",
    color: "#FFC107",
    phonetic: "/sænd/",
    guide: "SAND",
    type: "nature",
  },
  rock: {
    image: "images/rock.jpeg",
    chinese: "岩石",
    color: "#795548",
    phonetic: "/rɑːk/",
    guide: "RAHK",
    type: "nature",
  },
  stone: {
    image: "images/stone.jpeg",
    chinese: "石头",
    color: "#9E9E9E",
    phonetic: "/stoʊn/",
    guide: "STOHN",
    type: "nature",
  },
  flood: {
    image: "images/flood.jpeg",
    chinese: "洪水",
    color: "#2196F3",
    phonetic: "/flʌd/",
    guide: "FLUD",
    type: "nature",
  },
  drought: {
    image: "images/drought.jpeg",
    chinese: "干旱",
    color: "#FFC107",
    phonetic: "/draʊt/",
    guide: "DROWT",
    type: "nature",
  },
  earthquake: {
    image: "images/earthquake.jpeg",
    chinese: "地震",
    color: "#795548",
    phonetic: "/ˈɜːrθ.kweɪk/",
    guide: "URTH-kwayk",
    type: "nature",
  },
  volcano: {
    image: "images/volcano.jpeg",
    chinese: "火山",
    color: "#F44336",
    phonetic: "/vɑːlˈkeɪ.noʊ/",
    guide: "vahl-KAY-noh",
    type: "nature",
  },
  dew: {
    image: "images/dew.jpeg",
    chinese: "露水",
    color: "#2196F3",
    phonetic: "/duː/",
    guide: "DOO",
    type: "nature",
  },
  balloon: {
    image: "images/balloon.jpeg",
    chinese: "气球",
    color: "#F44336",
    phonetic: "/bəˈluːn/",
    guide: "buh-LOON",
    type: "other",
  },
  kite: {
    image: "images/kite.jpeg",
    chinese: "风筝",
    color: "#F44336",
    phonetic: "/kaɪt/",
    guide: "KYT",
    type: "other",
  },
  doll: {
    image: "images/doll.jpeg",
    chinese: "洋娃娃",
    color: "#E91E63",
    phonetic: "/dɑːl/",
    guide: "DAHL",
    type: "other",
  },
  puzzle: {
    image: "images/puzzle.jpeg",
    chinese: "拼图",
    color: "#FF9800",
    phonetic: "/ˈpʌz.əl/",
    guide: "PUZ-uhl",
    type: "other",
  },
  lego: {
    image: "images/lego.jpeg",
    chinese: "乐高",
    color: "#F44336",
    phonetic: "/ˈleɡ.oʊ/",
    guide: "LEG-oh",
    type: "other",
  },
  checkers: {
    image: "images/checkers.jpeg",
    chinese: "跳棋",
    color: "#F44336",
    phonetic: "/ˈtʃek.ərz/",
    guide: "CHEK-urz",
    type: "other",
  },
  marbles: {
    image: "images/marbles.jpeg",
    chinese: "弹珠",
    color: "#2196F3",
    phonetic: "/ˈmɑːr.bəlz/",
    guide: "MAR-buhlz",
    type: "other",
  },
  top: {
    image: "images/top.jpeg",
    chinese: "陀螺",
    color: "#F44336",
    phonetic: "/tɑːp/",
    guide: "TAHP",
    type: "other",
  },
  whistle: {
    image: "images/whistle.jpeg",
    chinese: "哨子",
    color: "#9E9E9E",
    phonetic: "/ˈwɪs.əl/",
    guide: "WIS-uhl",
    type: "other",
  },
  drum: {
    image: "images/drum.jpeg",
    chinese: "鼓",
    color: "#F44336",
    phonetic: "/drʌm/",
    guide: "DRUM",
    type: "other",
  },
  guitar: {
    image: "images/guitar.jpeg",
    chinese: "吉他",
    color: "#795548",
    phonetic: "/ɡɪˈtɑːr/",
    guide: "gi-TAR",
    type: "other",
  },
  piano: {
    image: "images/piano.jpeg",
    chinese: "钢琴",
    color: "#212121",
    phonetic: "/piˈæn.oʊ/",
    guide: "pee-AN-oh",
    type: "other",
  },
  violin: {
    image: "images/violin.jpeg",
    chinese: "小提琴",
    color: "#795548",
    phonetic: "/ˌvaɪ.əˈlɪn/",
    guide: "vy-uh-LIN",
    type: "other",
  },
  microscope: {
    image: "images/microscope.jpeg",
    chinese: "显微镜",
    color: "#9E9E9E",
    phonetic: "/ˈmaɪ.krə.skoʊp/",
    guide: "MY-kruh-skohp",
    type: "other",
  },
  telescope: {
    image: "images/telescope.jpeg",
    chinese: "望远镜",
    color: "#795548",
    phonetic: "/ˈtel.ɪ.skoʊp/",
    guide: "TEL-uh-skohp",
    type: "other",
  },
  compass: {
    image: "images/compass.jpeg",
    chinese: "指南针",
    color: "#795548",
    phonetic: "/ˈkʌm.pəs/",
    guide: "KUM-puhs",
    type: "other",
  },
  map: {
    image: "images/map.jpeg",
    chinese: "地图",
    color: "#4CAF50",
    phonetic: "/mæp/",
    guide: "MAP",
    type: "other",
  },
  hospital: {
    image: "images/hospital.jpeg",
    chinese: "医院",
    color: "#F44336",
    phonetic: "/ˈhɑː.spɪ.təl/",
    guide: "HAH-spi-tuhl",
    type: "other",
  },
  school: {
    image: "images/school.jpeg",
    chinese: "学校",
    color: "#2196F3",
    phonetic: "/skuːl/",
    guide: "SKOOL",
    type: "other",
  },
  library: {
    image: "images/library.jpeg",
    chinese: "图书馆",
    color: "#795548",
    phonetic: "/ˈlaɪ.brer.i/",
    guide: "LY-brer-ee",
    type: "other",
  },
  museum: {
    image: "images/museum.jpeg",
    chinese: "博物馆",
    color: "#795548",
    phonetic: "/mjuːˈziː.əm/",
    guide: "myoo-ZEE-uhm",
    type: "other",
  },
  zoo: {
    image: "images/zoo.jpeg",
    chinese: "动物园",
    color: "#4CAF50",
    phonetic: "/zuː/",
    guide: "ZOO",
    type: "other",
  },
  farm: {
    image: "images/farm.jpeg",
    chinese: "农场",
    color: "#4CAF50",
    phonetic: "/fɑːrm/",
    guide: "FARM",
    type: "other",
  },
  park: {
    image: "images/park.jpeg",
    chinese: "公园",
    color: "#4CAF50",
    phonetic: "/pɑːrk/",
    guide: "PARK",
    type: "other",
  },
  garden: {
    image: "images/garden.jpeg",
    chinese: "花园",
    color: "#4CAF50",
    phonetic: "/ˈɡɑːr.dən/",
    guide: "GAR-duhn",
    type: "other",
  },
  restaurant: {
    image: "images/restaurant.jpeg",
    chinese: "餐厅",
    color: "#F44336",
    phonetic: "/ˈres.tə.rɑːnt/",
    guide: "RES-tuh-rahnt",
    type: "other",
  },
  bakery: {
    image: "images/bakery.jpeg",
    chinese: "面包店",
    color: "#FFC107",
    phonetic: "/ˈbeɪ.kər.i/",
    guide: "BAY-kur-ee",
    type: "other",
  },
  cafe: {
    image: "images/cafe.jpeg",
    chinese: "咖啡馆",
    color: "#795548",
    phonetic: "/kæˈfeɪ/",
    guide: "ka-FAY",
    type: "other",
  },
  supermarket: {
    image: "images/supermarket.jpeg",
    chinese: "超市",
    color: "#2196F3",
    phonetic: "/ˈsuː.pər.mɑːr.kɪt/",
    guide: "SOO-pur-mar-kit",
    type: "other",
  },
  cinema: {
    image: "images/cinema.jpeg",
    chinese: "电影院",
    color: "#F44336",
    phonetic: "/ˈsɪn.ə.mə/",
    guide: "SIN-uh-muh",
    type: "other",
  },
  stadium: {
    image: "images/stadium.jpeg",
    chinese: "体育场",
    color: "#2196F3",
    phonetic: "/ˈsteɪ.di.əm/",
    guide: "STAY-dee-uhm",
    type: "other",
  },
  airport: {
    image: "images/airport.jpeg",
    chinese: "机场",
    color: "#2196F3",
    phonetic: "/ˈer.pɔːrt/",
    guide: "AIR-port",
    type: "other",
  },
  head: {
    image: "images/head.jpeg",
    chinese: "头",
    color: "#FFE082",
    phonetic: "/hed/",
    guide: "HED",
    type: "body",
  },
  hair: {
    image: "images/hair.jpeg",
    chinese: "头发",
    color: "#795548",
    phonetic: "/her/",
    guide: "HAIR",
    type: "body",
  },
  forehead: {
    image: "images/forehead.jpeg",
    chinese: "额头",
    color: "#FFE082",
    phonetic: "/ˈfɔːr.hed/",
    guide: "FOR-hed",
    type: "body",
  },
  eyebrow: {
    image: "images/eyebrow.jpeg",
    chinese: "眉毛",
    color: "#795548",
    phonetic: "/ˈaɪ.braʊ/",
    guide: "EYE-brow",
    type: "body",
  },
  eyelash: {
    image: "images/eyelash.jpeg",
    chinese: "睫毛",
    color: "#212121",
    phonetic: "/ˈaɪ.læʃ/",
    guide: "EYE-lash",
    type: "body",
  },
  cheek: {
    image: "images/cheek.jpeg",
    chinese: "脸颊",
    color: "#FF8A80",
    phonetic: "/tʃiːk/",
    guide: "CHEEK",
    type: "body",
  },
  chin: {
    image: "images/chin.jpeg",
    chinese: "下巴",
    color: "#FFE082",
    phonetic: "/tʃɪn/",
    guide: "CHIN",
    type: "body",
  },
  neck: {
    image: "images/neck.jpeg",
    chinese: "脖子",
    color: "#FFE082",
    phonetic: "/nek/",
    guide: "NEK",
    type: "body",
  },
  shoulder: {
    image: "images/shoulder.jpeg",
    chinese: "肩膀",
    color: "#FFE082",
    phonetic: "/ˈʃoʊl.dər/",
    guide: "SHOHL-dur",
    type: "body",
  },
  arm: {
    image: "images/arm.jpeg",
    chinese: "手臂",
    color: "#FFE082",
    phonetic: "/ɑːrm/",
    guide: "ARM",
    type: "body",
  },
  elbow: {
    image: "images/elbow.jpeg",
    chinese: "肘部",
    color: "#FFE082",
    phonetic: "/ˈel.boʊ/",
    guide: "EL-boh",
    type: "body",
  },
  wrist: {
    image: "images/wrist.jpeg",
    chinese: "手腕",
    color: "#FFE082",
    phonetic: "/rɪst/",
    guide: "RIST",
    type: "body",
  },
  hand: {
    image: "images/hand.jpeg",
    chinese: "手",
    color: "#FFE082",
    phonetic: "/hænd/",
    guide: "HAND",
    type: "body",
  },
  finger: {
    image: "images/finger.jpeg",
    chinese: "手指",
    color: "#FFE082",
    phonetic: "/ˈfɪŋ.ɡər/",
    guide: "FING-gur",
    type: "body",
  },
  thumb: {
    image: "images/thumb.jpeg",
    chinese: "拇指",
    color: "#FFE082",
    phonetic: "/θʌm/",
    guide: "THUM",
    type: "body",
  },
  chest: {
    image: "images/chest.jpeg",
    chinese: "胸部",
    color: "#FFE082",
    phonetic: "/tʃest/",
    guide: "CHEST",
    type: "body",
  },
  back: {
    image: "images/back.jpeg",
    chinese: "背部",
    color: "#FFE082",
    phonetic: "/bæk/",
    guide: "BAK",
    type: "body",
  },
  stomach: {
    image: "images/stomach.jpeg",
    chinese: "胃",
    color: "#FFE082",
    phonetic: "/ˈstʌm.ək/",
    guide: "STUM-uhk",
    type: "body",
  },
  hip: {
    image: "images/hip.jpeg",
    chinese: "臀部",
    color: "#FFE082",
    phonetic: "/hɪp/",
    guide: "HIP",
    type: "body",
  },
  knee: {
    image: "images/knee.jpeg",
    chinese: "膝盖",
    color: "#FFE082",
    phonetic: "/niː/",
    guide: "NEE",
    type: "body",
  },
  ankle: {
    image: "images/ankle.jpeg",
    chinese: "脚踝",
    color: "#FFE082",
    phonetic: "/ˈæŋ.kəl/",
    guide: "ANG-kuhl",
    type: "body",
  },
  heel: {
    image: "images/heel.jpeg",
    chinese: "脚跟",
    color: "#FFE082",
    phonetic: "/hiːl/",
    guide: "HEEL",
    type: "body",
  },
  toe: {
    image: "images/toe.jpeg",
    chinese: "脚趾",
    color: "#FFE082",
    phonetic: "/toʊ/",
    guide: "TOH",
    type: "body",
  },
  run: {
    image: "images/run.jpeg",
    chinese: "跑",
    color: "#F44336",
    phonetic: "/rʌn/",
    guide: "RUN",
    type: "action",
  },
  walk: {
    image: "images/walk.jpeg",
    chinese: "走",
    color: "#4CAF50",
    phonetic: "/wɔːk/",
    guide: "WAWK",
    type: "action",
  },
  jump: {
    image: "images/jump.jpeg",
    chinese: "跳",
    color: "#FF9800",
    phonetic: "/dʒʌmp/",
    guide: "JUMP",
    type: "action",
  },
  climb: {
    image: "images/climb.jpeg",
    chinese: "爬",
    color: "#795548",
    phonetic: "/klaɪm/",
    guide: "KLYM",
    type: "action",
  },
  crawl: {
    image: "images/crawl.jpeg",
    chinese: "爬行",
    color: "#795548",
    phonetic: "/krɔːl/",
    guide: "KRAWL",
    type: "action",
  },
  swim: {
    image: "images/swim.jpeg",
    chinese: "游泳",
    color: "#2196F3",
    phonetic: "/swɪm/",
    guide: "SWIM",
    type: "action",
  },
  dance: {
    image: "images/dance.jpeg",
    chinese: "跳舞",
    color: "#E91E63",
    phonetic: "/dæns/",
    guide: "DANS",
    type: "action",
  },
  sing: {
    image: "images/sing.jpeg",
    chinese: "唱歌",
    color: "#9C27B0",
    phonetic: "/sɪŋ/",
    guide: "SING",
    type: "action",
  },
  eat: {
    image: "images/eat.jpeg",
    chinese: "吃",
    color: "#FF9800",
    phonetic: "/iːt/",
    guide: "EET",
    type: "action",
  },
  drink: {
    image: "images/drink.jpeg",
    chinese: "喝",
    color: "#2196F3",
    phonetic: "/drɪŋk/",
    guide: "DRINK",
    type: "action",
  },
  bite: {
    image: "images/bite.jpeg",
    chinese: "咬",
    color: "#F44336",
    phonetic: "/baɪt/",
    guide: "BYT",
    type: "action",
  },
  lick: {
    image: "images/lick.jpeg",
    chinese: "舔",
    color: "#E91E63",
    phonetic: "/lɪk/",
    guide: "LIK",
    type: "action",
  },
  smell: {
    image: "images/smell.jpeg",
    chinese: "闻",
    color: "#9C27B0",
    phonetic: "/smel/",
    guide: "SMEL",
    type: "action",
  },
  look: {
    image: "images/look.jpeg",
    chinese: "看",
    color: "#2196F3",
    phonetic: "/lʊk/",
    guide: "LOOK",
    type: "action",
  },
  listen: {
    image: "images/listen.jpeg",
    chinese: "听",
    color: "#4CAF50",
    phonetic: "/ˈlɪs.ən/",
    guide: "LIS-uhn",
    type: "action",
  },
  touch: {
    image: "images/touch.jpeg",
    chinese: "触摸",
    color: "#FF9800",
    phonetic: "/tʌtʃ/",
    guide: "TUCH",
    type: "action",
  },
  hold: {
    image: "images/hold.jpeg",
    chinese: "拿",
    color: "#795548",
    phonetic: "/hoʊld/",
    guide: "HOHLD",
    type: "action",
  },
  catch: {
    image: "images/catch.jpeg",
    chinese: "接",
    color: "#F44336",
    phonetic: "/kætʃ/",
    guide: "KACH",
    type: "action",
  },
  throw: {
    image: "images/throw.jpeg",
    chinese: "扔",
    color: "#FF9800",
    phonetic: "/θroʊ/",
    guide: "THROH",
    type: "action",
  },
  kick: {
    image: "images/kick.jpeg",
    chinese: "踢",
    color: "#F44336",
    phonetic: "/kɪk/",
    guide: "KIK",
    type: "action",
  },
  hit: {
    image: "images/hit.jpeg",
    chinese: "打",
    color: "#F44336",
    phonetic: "/hɪt/",
    guide: "HIT",
    type: "action",
  },
  push: {
    image: "images/push.jpeg",
    chinese: "推",
    color: "#FF9800",
    phonetic: "/pʊʃ/",
    guide: "POOSH",
    type: "action",
  },
  pull: {
    image: "images/pull.jpeg",
    chinese: "拉",
    color: "#4CAF50",
    phonetic: "/pʊl/",
    guide: "POOL",
    type: "action",
  },
  lift: {
    image: "images/lift.jpeg",
    chinese: "举起",
    color: "#795548",
    phonetic: "/lɪft/",
    guide: "LIFT",
    type: "action",
  },
  carry: {
    image: "images/carry.jpeg",
    chinese: "搬运",
    color: "#795548",
    phonetic: "/ˈkær.i/",
    guide: "KAR-ee",
    type: "action",
  },
  drop: {
    image: "images/drop.jpeg",
    chinese: "掉落",
    color: "#F44336",
    phonetic: "/drɑːp/",
    guide: "DRAHP",
    type: "action",
  },
  press: {
    image: "images/press.jpeg",
    chinese: "按",
    color: "#9E9E9E",
    phonetic: "/pres/",
    guide: "PRES",
    type: "action",
  },
  break: {
    image: "images/break.jpeg",
    chinese: "打破",
    color: "#F44336",
    phonetic: "/breɪk/",
    guide: "BRAY",
    type: "action",
  },
  fix: {
    image: "images/fix.jpeg",
    chinese: "修理",
    color: "#4CAF50",
    phonetic: "/fɪks/",
    guide: "FIKS",
    type: "action",
  },
  build: {
    image: "images/build.jpeg",
    chinese: "建造",
    color: "#795548",
    phonetic: "/bɪld/",
    guide: "BILD",
    type: "action",
  },
  draw: {
    image: "images/draw.jpeg",
    chinese: "画",
    color: "#E91E63",
    phonetic: "/drɔː/",
    guide: "DRAW",
    type: "action",
  },
  write: {
    image: "images/write.jpeg",
    chinese: "写",
    color: "#2196F3",
    phonetic: "/raɪt/",
    guide: "RYT",
    type: "action",
  },
  read: {
    image: "images/read.jpeg",
    chinese: "读",
    color: "#4CAF50",
    phonetic: "/riːd/",
    guide: "REED",
    type: "action",
  },
  count: {
    image: "images/count.jpeg",
    chinese: "数",
    color: "#FF9800",
    phonetic: "/kaʊnt/",
    guide: "KOWNT",
    type: "action",
  },
  think: {
    image: "images/think.jpeg",
    chinese: "思考",
    color: "#9C27B0",
    phonetic: "/θɪŋk/",
    guide: "THINK",
    type: "action",
  },
  know: {
    image: "images/know.jpeg",
    chinese: "知道",
    color: "#2196F3",
    phonetic: "/noʊ/",
    guide: "NOH",
    type: "action",
  },
  remember: {
    image: "images/remember.jpeg",
    chinese: "记住",
    color: "#4CAF50",
    phonetic: "/rɪˈmem.bər/",
    guide: "ri-MEM-bur",
    type: "action",
  },
  forget: {
    image: "images/forget.jpeg",
    chinese: "忘记",
    color: "#F44336",
    phonetic: "/fərˈɡet/",
    guide: "fur-GET",
    type: "action",
  },
  sleep: {
    image: "images/sleep.jpeg",
    chinese: "睡觉",
    color: "#9E9E9E",
    phonetic: "/sliːp/",
    guide: "SLEEP",
    type: "action",
  },
  sit: {
    image: "images/sit.jpeg",
    chinese: "坐",
    color: "#795548",
    phonetic: "/sɪt/",
    guide: "SIT",
    type: "action",
  },
  stand: {
    image: "images/stand.jpeg",
    chinese: "站",
    color: "#4CAF50",
    phonetic: "/stænd/",
    guide: "STAND",
    type: "action",
  },
  bend: {
    image: "images/bend.jpeg",
    chinese: "弯曲",
    color: "#FF9800",
    phonetic: "/bend/",
    guide: "BEND",
    type: "action",
  },
  kneel: {
    image: "images/kneel.jpeg",
    chinese: "跪",
    color: "#795548",
    phonetic: "/niːl/",
    guide: "NEEL",
    type: "action",
  },
  stretch: {
    image: "images/stretch.jpeg",
    chinese: "伸展",
    color: "#2196F3",
    phonetic: "/stretʃ/",
    guide: "STRECH",
    type: "action",
  },
  wash: {
    image: "images/wash.jpeg",
    chinese: "洗",
    color: "#2196F3",
    phonetic: "/wɑːʃ/",
    guide: "WAHSH",
    type: "action",
  },
  clean: {
    image: "images/clean.jpeg",
    chinese: "清洁",
    color: "#4CAF50",
    phonetic: "/kliːn/",
    guide: "KLEEN",
    type: "action",
  },
  sweep: {
    image: "images/sweep.jpeg",
    chinese: "扫",
    color: "#795548",
    phonetic: "/swiːp/",
    guide: "SWEEP",
    type: "action",
  },
  wipe: {
    image: "images/wipe.jpeg",
    chinese: "擦",
    color: "#2196F3",
    phonetic: "/waɪp/",
    guide: "WYP",
    type: "action",
  },
  cook: {
    image: "images/cook.jpeg",
    chinese: "烹饪",
    color: "#FF9800",
    phonetic: "/kʊk/",
    guide: "KOOK",
    type: "action",
  },
  bake: {
    image: "images/bake.jpeg",
    chinese: "烤",
    color: "#FFC107",
    phonetic: "/beɪk/",
    guide: "BAYK",
    type: "action",
  },
  fry: {
    image: "images/fry.jpeg",
    chinese: "炸",
    color: "#FF9800",
    phonetic: "/fraɪ/",
    guide: "FRY",
    type: "action",
  },
  boil: {
    image: "images/boil.jpeg",
    chinese: "煮",
    color: "#2196F3",
    phonetic: "/bɔɪl/",
    guide: "BOYL",
    type: "action",
  },
  cut: {
    image: "images/cut.jpeg",
    chinese: "切",
    color: "#F44336",
    phonetic: "/kʌt/",
    guide: "KUT",
    type: "action",
  },
  peel: {
    image: "images/peel.jpeg",
    chinese: "削皮",
    color: "#FF9800",
    phonetic: "/piːl/",
    guide: "PEEL",
    type: "action",
  },
  pour: {
    image: "images/pour.jpeg",
    chinese: "倒",
    color: "#2196F3",
    phonetic: "/pɔːr/",
    guide: "POR",
    type: "action",
  },
  mix: {
    image: "images/mix.jpeg",
    chinese: "混合",
    color: "#795548",
    phonetic: "/mɪks/",
    guide: "MIKS",
    type: "action",
  },
  stir: {
    image: "images/stir.jpeg",
    chinese: "搅拌",
    color: "#795548",
    phonetic: "/stɜːr/",
    guide: "STUR",
    type: "action",
  },
  spread: {
    image: "images/spread.jpeg",
    chinese: "涂抹",
    color: "#FFC107",
    phonetic: "/spred/",
    guide: "SPRED",
    type: "action",
  },
  plant: {
    image: "images/plant.jpeg",
    chinese: "种植",
    color: "#4CAF50",
    phonetic: "/plænt/",
    guide: "PLANT",
    type: "action",
  },
  dig: {
    image: "images/dig.jpeg",
    chinese: "挖",
    color: "#795548",
    phonetic: "/dɪɡ/",
    guide: "DIG",
    type: "action",
  },
  hide: {
    image: "images/hide.jpeg",
    chinese: "隐藏",
    color: "#795548",
    phonetic: "/haɪd/",
    guide: "HYD",
    type: "action",
  },
  find: {
    image: "images/find.jpeg",
    chinese: "找到",
    color: "#4CAF50",
    phonetic: "/faɪnd/",
    guide: "FYND",
    type: "action",
  },
  search: {
    image: "images/search.jpeg",
    chinese: "搜索",
    color: "#2196F3",
    phonetic: "/sɜːrtʃ/",
    guide: "SURCH",
    type: "action",
  },
  give: {
    image: "images/give.jpeg",
    chinese: "给",
    color: "#4CAF50",
    phonetic: "/ɡɪv/",
    guide: "GIV",
    type: "action",
  },
  take: {
    image: "images/take.jpeg",
    chinese: "拿",
    color: "#FF9800",
    phonetic: "/teɪk/",
    guide: "TAYK",
    type: "action",
  },
  bring: {
    image: "images/bring.jpeg",
    chinese: "带来",
    color: "#4CAF50",
    phonetic: "/brɪŋ/",
    guide: "BRING",
    type: "action",
  },
  send: {
    image: "images/send.jpeg",
    chinese: "发送",
    color: "#2196F3",
    phonetic: "/send/",
    guide: "SEND",
    type: "action",
  },
  receive: {
    image: "images/receive.jpeg",
    chinese: "接收",
    color: "#4CAF50",
    phonetic: "/rɪˈsiːv/",
    guide: "ri-SEEV",
    type: "action",
  },
  buy: {
    image: "images/buy.jpeg",
    chinese: "买",
    color: "#FF9800",
    phonetic: "/baɪ/",
    guide: "BY",
    type: "action",
  },
  sell: {
    image: "images/sell.jpeg",
    chinese: "卖",
    color: "#F44336",
    phonetic: "/sel/",
    guide: "SEL",
    type: "action",
  },
  pay: {
    image: "images/pay.jpeg",
    chinese: "支付",
    color: "#4CAF50",
    phonetic: "/peɪ/",
    guide: "PAY",
    type: "action",
  },
  earn: {
    image: "images/earn.jpeg",
    chinese: "赚",
    color: "#4CAF50",
    phonetic: "/ɜːrn/",
    guide: "URN",
    type: "action",
  },
  save: {
    image: "images/save.jpeg",
    chinese: "节省",
    color: "#2196F3",
    phonetic: "/seɪv/",
    guide: "SAYV",
    type: "action",
  },
  spend: {
    image: "images/spend.jpeg",
    chinese: "花费",
    color: "#F44336",
    phonetic: "/spend/",
    guide: "SPEND",
    type: "action",
  },
  help: {
    image: "images/help.jpeg",
    chinese: "帮助",
    color: "#4CAF50",
    phonetic: "/help/",
    guide: "HELP",
    type: "action",
  },
  share: {
    image: "images/share.jpeg",
    chinese: "分享",
    color: "#FF9800",
    phonetic: "/ʃer/",
    guide: "SHAIR",
    type: "action",
  },
  laugh: {
    image: "images/laugh.jpeg",
    chinese: "笑",
    color: "#FFC107",
    phonetic: "/læf/",
    guide: "LAF",
    type: "action",
  },
  cry: {
    image: "images/cry.jpeg",
    chinese: "哭",
    color: "#2196F3",
    phonetic: "/kraɪ/",
    guide: "KRY",
    type: "action",
  },
  smile: {
    image: "images/smile.jpeg",
    chinese: "微笑",
    color: "#FFC107",
    phonetic: "/smaɪl/",
    guide: "SMYL",
    type: "action",
  },
  one: {
    image: "images/one.jpeg",
    chinese: "一",
    color: "#2196F3",
    phonetic: "/wʌn/",
    guide: "WUN",
    type: "number",
  },
  two: {
    image: "images/two.jpeg",
    chinese: "二",
    color: "#2196F3",
    phonetic: "/tuː/",
    guide: "TOO",
    type: "number",
  },
  three: {
    image: "images/three.jpeg",
    chinese: "三",
    color: "#2196F3",
    phonetic: "/θriː/",
    guide: "THREE",
    type: "number",
  },
  four: {
    image: "images/four.jpeg",
    chinese: "四",
    color: "#2196F3",
    phonetic: "/fɔːr/",
    guide: "FOUR",
    type: "number",
  },
  five: {
    image: "images/five.jpeg",
    chinese: "五",
    color: "#2196F3",
    phonetic: "/faɪv/",
    guide: "FYV",
    type: "number",
  },
  six: {
    image: "images/six.jpeg",
    chinese: "六",
    color: "#2196F3",
    phonetic: "/sɪks/",
    guide: "SIKS",
    type: "number",
  },
  seven: {
    image: "images/seven.jpeg",
    chinese: "七",
    color: "#2196F3",
    phonetic: "/ˈsev.ən/",
    guide: "SEV-en",
    type: "number",
  },
  eight: {
    image: "images/eight.jpeg",
    chinese: "八",
    color: "#2196F3",
    phonetic: "/eɪt/",
    guide: "AYT",
    type: "number",
  },
  nine: {
    image: "images/nine.jpeg",
    chinese: "九",
    color: "#2196F3",
    phonetic: "/naɪn/",
    guide: "NYN",
    type: "number",
  },
  ten: {
    image: "images/ten.jpeg",
    chinese: "十",
    color: "#2196F3",
    phonetic: "/ten/",
    guide: "TEN",
    type: "number",
  },
  eleven: {
    image: "images/eleven.jpeg",
    chinese: "十一",
    color: "#2196F3",
    phonetic: "/ɪˈlev.ən/",
    guide: "i-LEV-en",
    type: "number",
  },
  twelve: {
    image: "images/twelve.jpeg",
    chinese: "十二",
    color: "#2196F3",
    phonetic: "/twelv/",
    guide: "TWELV",
    type: "number",
  },
  thirteen: {
    image: "images/thirteen.jpeg",
    chinese: "十三",
    color: "#2196F3",
    phonetic: "/θɜːrˈtiːn/",
    guide: "thur-TEEN",
    type: "number",
  },
  fourteen: {
    image: "images/fourteen.jpeg",
    chinese: "十四",
    color: "#2196F3",
    phonetic: "/fɔːrˈtiːn/",
    guide: "for-TEEN",
    type: "number",
  },
  fifteen: {
    image: "images/fifteen.jpeg",
    chinese: "十五",
    color: "#2196F3",
    phonetic: "/fɪfˈtiːn/",
    guide: "fif-TEEN",
    type: "number",
  },
  sixteen: {
    image: "images/sixteen.jpeg",
    chinese: "十六",
    color: "#2196F3",
    phonetic: "/sɪksˈtiːn/",
    guide: "siks-TEEN",
    type: "number",
  },
  seventeen: {
    image: "images/seventeen.jpeg",
    chinese: "十七",
    color: "#2196F3",
    phonetic: "/ˌsev.ənˈtiːn/",
    guide: "sev-en-TEEN",
    type: "number",
  },
  eighteen: {
    image: "images/eighteen.jpeg",
    chinese: "十八",
    color: "#2196F3",
    phonetic: "/ˌeɪˈtiːn/",
    guide: "ay-TEEN",
    type: "number",
  },
  nineteen: {
    image: "images/nineteen.jpeg",
    chinese: "十九",
    color: "#2196F3",
    phonetic: "/ˌnaɪnˈtiːn/",
    guide: "nyn-TEEN",
    type: "number",
  },
  twenty: {
    image: "images/twenty.jpeg",
    chinese: "二十",
    color: "#2196F3",
    phonetic: "/ˈtwen.ti/",
    guide: "TWEN-tee",
    type: "number",
  },
  thirty: {
    image: "images/thirty.jpeg",
    chinese: "三十",
    color: "#2196F3",
    phonetic: "/ˈθɜːr.ti/",
    guide: "THUR-tee",
    type: "number",
  },
  forty: {
    image: "images/forty.jpeg",
    chinese: "四十",
    color: "#2196F3",
    phonetic: "/ˈfɔːr.ti/",
    guide: "FOR-tee",
    type: "number",
  },
  fifty: {
    image: "images/fifty.jpeg",
    chinese: "五十",
    color: "#2196F3",
    phonetic: "/ˈfɪf.ti/",
    guide: "FIF-tee",
    type: "number",
  },
  sixty: {
    image: "images/sixty.jpeg",
    chinese: "六十",
    color: "#2196F3",
    phonetic: "/ˈsɪks.ti/",
    guide: "SIKS-tee",
    type: "number",
  },
  seventy: {
    image: "images/seventy.jpeg",
    chinese: "七十",
    color: "#2196F3",
    phonetic: "/ˈsev.ən.ti/",
    guide: "SEV-en-tee",
    type: "number",
  },
  eighty: {
    image: "images/eighty.jpeg",
    chinese: "八十",
    color: "#2196F3",
    phonetic: "/ˈeɪ.ti/",
    guide: "AY-tee",
    type: "number",
  },
  ninety: {
    image: "images/ninety.jpeg",
    chinese: "九十",
    color: "#2196F3",
    phonetic: "/ˈnaɪn.ti/",
    guide: "NYN-tee",
    type: "number",
  },
  hundred: {
    image: "images/hundred.jpeg",
    chinese: "百",
    color: "#2196F3",
    phonetic: "/ˈhʌn.drəd/",
    guide: "HUN-dred",
    type: "number",
  },
  thousand: {
    image: "images/thousand.jpeg",
    chinese: "千",
    color: "#2196F3",
    phonetic: "/ˈθaʊ.zənd/",
    guide: "THOW-zend",
    type: "number",
  },
  spring: {
    image: "images/spring.jpeg",
    chinese: "春天",
    color: "#4CAF50",
    phonetic: "/sprɪŋ/",
    guide: "SPRING",
    type: "nature",
  },
  summer: {
    image: "images/summer.jpeg",
    chinese: "夏天",
    color: "#FF9800",
    phonetic: "/ˈsʌm.ər/",
    guide: "SUM-ur",
    type: "nature",
  },
  autumn: {
    image: "images/autumn.jpeg",
    chinese: "秋天",
    color: "#FFC107",
    phonetic: "/ˈɔː.təm/",
    guide: "AW-tum",
    type: "nature",
  },
  winter: {
    image: "images/winter.jpeg",
    chinese: "冬天",
    color: "#2196F3",
    phonetic: "/ˈwɪn.tər/",
    guide: "WIN-tur",
    type: "nature",
  },
  red: {
    image: "images/red.jpeg",
    chinese: "红色",
    color: "#FF0000",
    phonetic: "/red/",
    guide: "RED",
    type: "color",
  },
  green: {
    image: "images/green.jpeg",
    chinese: "绿色",
    color: "#00FF00",
    phonetic: "/ɡriːn/",
    guide: "GREEN",
    type: "color",
  },
  yellow: {
    image: "images/yellow.jpeg",
    chinese: "黄色",
    color: "#FFFF00",
    phonetic: "/ˈjel.oʊ/",
    guide: "YEL-oh",
    type: "color",
  },
  blue: {
    image: "images/blue.jpeg",
    chinese: "蓝色",
    color: "#0000FF",
    phonetic: "/bluː/",
    guide: "BLUE",
    type: "color",
  },
  purple: {
    image: "images/purple.jpeg",
    chinese: "紫色",
    color: "#800080",
    phonetic: "/ˈpɜːr.pəl/",
    guide: "PUR-puhl",
    type: "color",
  },
  black: {
    image: "images/black.jpeg",
    chinese: "黑色",
    color: "#000000",
    phonetic: "/blæk/",
    guide: "BLACK",
    type: "color",
  },
  white: {
    image: "images/white.jpeg",
    chinese: "白色",
    color: "#FFFFFF",
    phonetic: "/waɪt/",
    guide: "WHITE",
    type: "color",
  },
  pink: {
    image: "images/pink.jpeg",
    chinese: "粉色",
    color: "#FFC0CB",
    phonetic: "/pɪŋk/",
    guide: "PINK",
    type: "color",
  },
  brown: {
    image: "images/brown.jpeg",
    chinese: "棕色",
    color: "#A52A2A",
    phonetic: "/braʊn/",
    guide: "BROWN",
    type: "color",
  },
  gray: {
    image: "images/gray.jpeg",
    chinese: "灰色",
    color: "#808080",
    phonetic: "/ɡreɪ/",
    guide: "GRAY",
    type: "color",
  },
  gold: {
    image: "images/gold.jpeg",
    chinese: "金色",
    color: "#FFD700",
    phonetic: "/ɡoʊld/",
    guide: "GOLD",
    type: "color",
  },
  silver: {
    image: "images/silver.jpeg",
    chinese: "银色",
    color: "#C0C0C0",
    phonetic: "/ˈsɪl.vər/",
    guide: "SIL-vur",
    type: "color",
  },
  axe: {
    image: "images/axe.jpeg",
    chinese: "斧头",
    color: "#8B4513",
    phonetic: "/æks/",
    guide: "ax",
    type: "household",
  },
  envelope: {
    image: "images/envelope.jpeg",
    chinese: "信封",
    color: "#F5F5DC",
    phonetic: "/ˈen.və.loʊp/",
    guide: "EN-vuh-lope",
    type: "household",
  },
  fan: {
    image: "images/fan.jpeg",
    chinese: "风扇",
    color: "#87CEEB",
    phonetic: "/fæn/",
    guide: "fan",
    type: "household",
  },
  gift: {
    image: "images/gift.jpeg",
    chinese: "礼物",
    color: "#FF69B4",
    phonetic: "/ɡɪft/",
    guide: "gift",
    type: "household",
  },
  ice: {
    image: "images/ice.jpeg",
    chinese: "冰",
    color: "#E0FFFF",
    phonetic: "/aɪs/",
    guide: "ice",
    type: "nature",
  },
  jam: {
    image: "images/jam.jpeg",
    chinese: "果酱",
    color: "#B22222",
    phonetic: "/dʒæm/",
    guide: "jam",
    type: "food",
  },
  boy: {
    image: "images/boy.jpeg",
    chinese: "男孩",
    color: "#4169E1",
    phonetic: "/bɔɪ/",
    guide: "boy",
    type: "people",
  },
  girl: {
    image: "images/girl.jpeg",
    chinese: "女孩",
    color: "#FF69B4",
    phonetic: "/ɡɜːrl/",
    guide: "gurl",
    type: "people",
  },
  ink: {
    image: "images/ink.jpeg",
    chinese: "墨水",
    color: "#000080",
    phonetic: "/ɪŋk/",
    guide: "ink",
    type: "household",
  },
  net: {
    image: "images/net.jpeg",
    chinese: "网",
    color: "#808080",
    phonetic: "/net/",
    guide: "net",
    type: "other",
  },
  ostrich: {
    image: "images/ostrich.jpeg",
    chinese: "鸵鸟",
    color: "#D2B48C",
    phonetic: "/ˈɑː.strɪtʃ/",
    guide: "OS-trich",
    type: "animal",
  },
  ox: {
    image: "images/ox.jpeg",
    chinese: "公牛",
    color: "#8B4513",
    phonetic: "/ɑːks/",
    guide: "ox",
    type: "animal",
  },
  pen: {
    image: "images/pen.jpeg",
    chinese: "钢笔",
    color: "#000080",
    phonetic: "/pen/",
    guide: "pen",
    type: "household",
  },
  pencil: {
    image: "images/pencil.jpeg",
    chinese: "铅笔",
    color: "#FFD700",
    phonetic: "/ˈpen.səl/",
    guide: "PEN-suhl",
    type: "household",
  },
  robot: {
    image: "images/robot.jpeg",
    chinese: "机器人",
    color: "#C0C0C0",
    phonetic: "/ˈroʊ.bɑːt/",
    guide: "ROH-bot",
    type: "other",
  },
  basketball: {
    image: "images/basketball.jpeg",
    chinese: "篮球",
    color: "#FF8C00",
    phonetic: "/ˈbæs.kɪt.bɔːl/",
    guide: "BAS-kit-bawl",
    type: "other",
  },
  football: {
    image: "images/football.jpeg",
    chinese: "足球",
    color: "#FFFFFF",
    phonetic: "/ˈfʊt.bɔːl/",
    guide: "FOOT-bawl",
    type: "other",
  },
  badminton: {
    image: "images/badminton.jpeg",
    chinese: "羽毛球",
    color: "#F0E68C",
    phonetic: "/ˈbæd.mɪn.tən/",
    guide: "BAD-min-tun",
    type: "other",
  },
  rose: {
    image: "images/rose.jpeg",
    chinese: "玫瑰",
    color: "#FF1493",
    phonetic: "/roʊz/",
    guide: "rohz",
    type: "nature",
  },
  tent: {
    image: "images/tent.jpeg",
    chinese: "帐篷",
    color: "#228B22",
    phonetic: "/tent/",
    guide: "tent",
    type: "household",
  },
  box: {
    image: "images/box.jpeg",
    chinese: "盒子",
    color: "#CD853F",
    phonetic: "/bɑːks/",
    guide: "box",
    type: "household",
  },
  nut: {
    image: "images/nut.jpeg",
    chinese: "坚果",
    color: "#8B4513",
    phonetic: "/nʌt/",
    guide: "nuht",
    type: "food",
  },
  fire: {
    image: "images/fire.jpeg",
    chinese: "火",
    color: "#FF4500",
    phonetic: "/ˈfaɪər/",
    guide: "FYE-ur",
    type: "nature",
  },
  yam: {
    image: "images/yam.jpeg",
    chinese: "山药",
    color: "#D2B48C",
    phonetic: "/jæm/",
    guide: "yam",
    type: "vegetable",
  },
  ram: {
    image: "images/ram.jpeg",
    chinese: "公羊",
    color: "#A0522D",
    phonetic: "/ræm/",
    guide: "ram",
    type: "animal",
  },
  dam: {
    image: "images/dam.jpeg",
    chinese: "水坝",
    color: "#4682B4",
    phonetic: "/dæm/",
    guide: "dam",
    type: "nature",
  },
  pan: {
    image: "images/pan.jpeg",
    chinese: "平底锅",
    color: "#696969",
    phonetic: "/pæn/",
    guide: "pan",
    type: "household",
  },
  can: {
    image: "images/can.jpeg",
    chinese: "罐子",
    color: "#C0C0C0",
    phonetic: "/kæn/",
    guide: "kan",
    type: "household",
  },
  rag: {
    image: "images/rag.jpeg",
    chinese: "抹布",
    color: "#A9A9A9",
    phonetic: "/ræɡ/",
    guide: "rag",
    type: "household",
  },
  pad: {
    image: "images/pad.jpeg",
    chinese: "笔记本",
    color: "#F5F5DC",
    phonetic: "/pæd/",
    guide: "pad",
    type: "household",
  },
  bag: {
    image: "images/bag.jpeg",
    chinese: "包",
    color: "#8B4513",
    phonetic: "/bæɡ/",
    guide: "bag",
    type: "household",
  },
  tap: {
    image: "images/tap.jpeg",
    chinese: "水龙头",
    color: "#B0C4DE",
    phonetic: "/tæp/",
    guide: "tap",
    type: "household",
  },
  nap: {
    image: "images/nap.jpeg",
    chinese: "小睡",
    color: "#87CEEB",
    phonetic: "/næp/",
    guide: "nap",
    type: "action",
  },
  mat: {
    image: "images/mat.jpeg",
    chinese: "垫子",
    color: "#D2B48C",
    phonetic: "/mæt/",
    guide: "mat",
    type: "household",
  },
  vet: {
    image: "images/vet.jpeg",
    chinese: "兽医",
    color: "#2E8B57",
    phonetic: "/vet/",
    guide: "vet",
    type: "people",
  },
  pet: {
    image: "images/pet.jpeg",
    chinese: "宠物",
    color: "#FFB6C1",
    phonetic: "/pet/",
    guide: "pet",
    type: "animal",
  },
  lip: {
    image: "images/lip.jpeg",
    chinese: "嘴唇",
    color: "#FFC0CB",
    phonetic: "/lɪp/",
    guide: "lip",
    type: "body",
  },
  sip: {
    image: "images/sip.jpeg",
    chinese: "小口喝",
    color: "#00CED1",
    phonetic: "/sɪp/",
    guide: "sip",
    type: "action",
  },
  tip: {
    image: "images/tip.jpeg",
    chinese: "指尖",
    color: "#FFDAB9",
    phonetic: "/tɪp/",
    guide: "tip",
    type: "body",
  },
  rip: {
    image: "images/rip.jpeg",
    chinese: "撕",
    color: "#CD5C5C",
    phonetic: "/rɪp/",
    guide: "rip",
    type: "action",
  },
  bib: {
    image: "images/bib.jpeg",
    chinese: "围嘴",
    color: "#FF69B4",
    phonetic: "/bɪb/",
    guide: "bib",
    type: "clothing",
  },
  rib: {
    image: "images/rib.jpeg",
    chinese: "肋骨",
    color: "#F5DEB3",
    phonetic: "/rɪb/",
    guide: "rib",
    type: "body",
  },
  kid: {
    image: "images/kid.jpeg",
    chinese: "小孩",
    color: "#FFA07A",
    phonetic: "/kɪd/",
    guide: "kid",
    type: "people",
  },
  lid: {
    image: "images/lid.jpeg",
    chinese: "盖子",
    color: "#D3D3D3",
    phonetic: "/lɪd/",
    guide: "lid",
    type: "household",
  },
  yak: {
    image: "images/yak.jpeg",
    chinese: "牦牛",
    color: "#8B4513",
    phonetic: "/jæk/",
    guide: "YAK",
    type: "animal",
  },
  fig: {
    image: "images/fig.jpeg",
    chinese: "无花果",
    color: "#8B4513",
    phonetic: "/fɪɡ/",
    guide: "FIG",
    type: "fruit",
  },
  tennis: {
    image: "images/tennis.jpeg",
    chinese: "网球",
    color: "#8B4513",
    phonetic: "/ˈten.ɪs/",
    guide: "TEN-iss",
    type: "other",
  },
  leopard: {
    image: "images/leopard.jpeg",
    chinese: "豹子",
    color: "#FF9800",
    phonetic: "/ˈlep.ərd/",
    guide: "LEP-urd",
    type: "animal",
  },
};

window.wordData = wordData;
